### ISSUE TITLE
Which JSAPI FeatureLayer methods should be supported in esriFeatureLayer?

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#100]
Stemming from issue #97, which JSAPI FeatureLayer methods should be supported in esriFeatureLayer?  If it doesn't overstep the goals of this repo in terms of adding on a bunch of new layer functionality, it might be nice to include a few that are commonly used.

**setters**
- [x] `setDefinitionExpression()`
- [x] `setOpacity()`
- [x] `setVisibility()`
- ~~[ ] `setRenderer()`~~

~~**getters**~~
- ~~?~~

~~**other**~~
- ~~?~~

Would be worthwhile to look over PR #68 to see if anything happens to overlap.  At a quick glance, I don't think it will much, but the symbols or renderers might later.

**Comment by tomwayson** [comment]
Generally speaking I'm not in favor of proactively expanding the footprint right now. I'd prefer requests to come in from the community.

That said, definition expression and opacity are on par w/ visibility in terms of usefulness and difficulty. I'd say we want to include them by v1.0.

Setting renderers would also be very useful, but it's a can 'o' worms that I don't want to open at this time.

**Comment by jwasil** [comment]
@tomwayson, awesome, I think we're on the same page here. Once we were discussing visibility and definitionExpression, opacity crossed my mind as being similar and commonly used. After that, I just wanted to 2x check there wasn't anything else within-scope or obvious I was missing that could be vetted in a central place. :smiley: Thanks.

**Comment by tomwayson** [comment]
Yeah, opacity should be an easy win. Good idea. It also would demonstrate two way binding to a decimal value, rounding out the trifecta with the others ones being boolean and string.
