### ISSUE TITLE
Look into using a tool to generate docs from comments

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#107]
JSDoc?

**Comment by jwasil** [comment]
possibly jsdoc and ngdoc?  Another place to research: ["Angular Wiki: Writing AngularJS Documentation"](https://github.com/angular/angular.js/wiki/Writing-AngularJS-Documentation)

**Comment by jwasil** [comment]
Some processors and gulp solutions if we use ngDoc annotations in the code:
- https://www.npmjs.com/package/gulp-ngdocs
- https://www.npmjs.com/package/generator-ngdoc (has a promising working docs sample, yeoman that uses Dgeni)
- or, dive right into Dgeni itself https://github.com/angular/dgeni

**Comment by jwasil** [comment]
@tomwayson, check this out if you're curious what a generated docs page can look like.  I started experimenting with gulp-ngdocs (first bullet in previous comment) over in this branch:

https://github.com/Esri/angular-esri-map/tree/generate-docs

You'll have to update your bower deps, then you can try `gulp ngdocs`, and finally view the built site in a new directory (for now /ngdocs_test).  Note that there's more to see for the **esriLoader** currently.  That and the **esriLegend** already had some stubbed out ngdoc comments from previous commits, which I massaged to play nice with all this.

**Comment by jwasil** [comment]
Resolved in PR #142 to look into and setup a tool for doc generation.
