### ISSUE TITLE
Is there a way to load secure layers?

### ISSUE THREAD

**Issue by jmrroy** [Esri/angular-esri-map#113]
I am currently developing an app that uses secure layers, with the Arcgis API for javascript  based on this example : https://developers.arcgis.com/javascript/jssamples/widget_identitymanager_client_side.html .
I use angular and would use "angular-esri-map" that I have tested.
Did I miss something and there is already a way to use angular-esri-map with secure layer?
Or do you plan to integrate the Identity manager in the near future?

**Comment by tomwayson** [comment]
@jmrroy 

There's no plan to any any API (dirctives/services) around the identity manager in [the roadmap](https://github.com/Esri/angular-esri-map/milestones), however you should be able to replicate the functionality in that sample today using the current API. Take a look at how the [web map example](http://esri.github.io/angular-esri-map/#/examples/web-map) uses the `esriLoader` to load the Extent class. Your controller could use that same pattern to load `esri/IdentityManager` before adding layers to the map.

**Comment by jmrroy** [comment]
Thank you, I'll try to do it like that!

**Comment by tomwayson** [comment]
It occurs to me that b/c you need to initialize the identity manager *before* the map/layers load, you may need to execute that code in a route's `resolve` (if you're using router), or maybe in `angular.run()`. Let me know if you hit any issues.

**Comment by jmrroy** [comment]
Hi, 
I successfully integrate the identity manager based on this example: https://developers.arcgis.com/javascript/jssamples/widget_identitymanager_client_side.html 
I put my code in a angular service that I load in a resolve route and it works pretty well. 

One inconvenient is that I think that you have to authentify to arcgisonline even if you are looking for a not secure layer. It would be more efficient that my service only load if a token is required. I'm not sure about this last point because I only work with secure layers.

**Comment by tomwayson** [comment]
That's great!

W/o seeing your code it's hard for me to tell, however, it should not be an issue to init the identity manager from serialized credentials stored locally, even when you are using unsecured services. That should not prompt the user from credentials unless the stored credentials have expired.

I'm closing this issue for now.
