### ISSUE TITLE
Fix docs examples and re-publish

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#117]
- [x] update example page for dynamic map service layer to match test page
- [x] No basemap example is missing from JSON, others?
- [x] republish to gh-pages

**Comment by tomwayson** [comment]
not exactly related, but leaving a note to self here: update CHANGELOG.md w/ additions in 9f79bdb69d0f2c0aed23ccdd68240828dce95587

**Comment by jwasil** [comment]
@tomwayson leaving another note to please update CHANGELOG with PR #118.  I figured it would make more sense to note the changes to the esriInfoTemplate and esriFeatureLayer while writing up the all-inclusive efforts you mention above.

**Comment by tomwayson** [comment]
fixed in c69329b97ec0cd29d7aeb02a60f6691b2a525842
