### ISSUE TITLE
require is 'undefined'

### ISSUE THREAD

**Issue by snobrdinrtiste** [Esri/angular-esri-map#122]
Can anyone tell me why I keep getting that error?
It always error out after i link to the src file 

<script src="bower_components/angular-esri-map/dist/angular-esri-map.js"></script>

i even tried the minified version

**Comment by tomwayson** [comment]
@snobrdinrtiste did you also [include the JSAPI script tag](https://github.com/Esri/angular-esri-map/blob/master/docs/index.html#L82)?

**Comment by snobrdinrtiste** [comment]
Hi Tom,
Yes ... I did that and have tried everything except for downloading the init.js file to run locally... i will try that and see if it works... will post back my results.

**Comment by snobrdinrtiste** [comment]
even downloading the  3.14compact/init.js file locally doesn't work....
problem is with dojo... 
once i include the ArcGIS Javascript API init.js file (locally or thru: http://js.arcgis.com/3.14compact)... thats when i get dojo errors...
so do i need to include the dojo toolkit js too???

**Comment by tomwayson** [comment]
no, you should not, Dojo is bundled into the JSAPI. You cannot just download that file locally though.

Can you post a JSFiddle or plunker that shows the issue?

**Comment by snobrdinrtiste** [comment]
atm... i'm trying to breakdown the js includes on my angular index.htm page to try to isolate the error thats happening... i will post a plunkr if i am not able to get this working soon... thanks for your help Tom

**Comment by snobrdinrtiste** [comment]
Tom,
I have copied the same code in the example on the main page into an index.html to test... and i'm referencing the "angular-esri-map.js" from the bower install.  I am getting the same "require is undefined" error in IE's console.
Any ideas why?

**Comment by snobrdinrtiste** [comment]
Ok so it seems that the issue is on the network side here at work... for some reason, the proxy server is blocking the ArcGIS JSAPI ...  go figure...
