### ISSUE TITLE
Single page application with more than one map?

### ISSUE THREAD

**Issue by Kollibri** [Esri/angular-esri-map#125]
I'm trying to create a single page application with more than one map.  But I'm running into problems with the extent between the two maps being shared.  For instance, if I change the extent in map "A", then switch over the map "B", they will be the same.

Both maps are within their own controller.

I'm sure this is something basic to do with angular scopes, etc that I'm just not understanding yet.  Is there a possibility you could set up an example showing how you'd implement this?

**Comment by tomwayson** [comment]
See [this plunker](http://plnkr.co/edit/9mYVslnvoJ4GSwJXZKtw?p=preview)

**Comment by Kollibri** [comment]
@tomwayson  Thanks for the plunker.  It's not exactly what I'm trying to do and it's my fault for not explaining properly.  I actually have two maps on different angular /routes, so it's like they are on different "pages" of the application.

After discussing this with my teammates we've decided we don't require this functionality after all so I'm going to close this ticket.  It's ok for the map to just reset everytime it's loaded.
