### ISSUE TITLE
Single page app with map, after changing to different /route and returning to map, lose layers

### ISSUE THREAD

**Issue by Kollibri** [Esri/angular-esri-map#126]
I have a [plunker](http://plnkr.co/edit/pG30tPDQh5Vy6gWzUlQz?p=preview) here that shows the problem described below.

If you click on "interactive map" at the top, you will see a map with multiple dynamic layers.  If you then click back to "home" or "about" and then click back into "interactive map", the dynamic layers are gone.  If you look in the console, you'll see errors about how it can't connect to the invalid URL.  The URL for the map service is changed from the actual bound value to just the text of the angular binding.

I'm not sure how to stop this.  It's setup for two way binding, not "one-time" binding.  Any ideas why the map layer directive is not reading the value for the angular binding on subsequent loads?

**Comment by Kollibri** [comment]
I've been playing around with this and I think this is something to do with the attributes using the binding "{{ }}" and the values not being interpolated by the time the layer is created.  According to [this](http://stackoverflow.com/questions/14300986/angularjs-directive-isolated-scope-and-attrs) the following issue may be at hand:
"attribute values with {{}}s will cause you problems, since they will not be interpolated. 
Suppose we have <my-directive name="My name is {{name}}"> and the parent scope has $scope.name='Mark'. Then, inside the linking function, console.log(attrs.name) results in undefined. 
If name is an isolate scope property defined with '@', then attrs.$observe('name', function(val) { console.log(val) }) results in My name is Mark. (Note that inside the linking function, $observe() must be used to get the interpolated value.)"

I've been trying to play around with the "esriDynamicMapServiceLayer" directive near the place where the call to instantiate the layer is made.  Trying to get it to use $observe instead of just reading directly from $attrs.url but haven't been successful so far.  

I thought I would post what I've found so far here in the hopes that @tomwayson or @jwasil might have some ideas on how to fix it.

**Comment by Kollibri** [comment]
Well, I got it fixed by changing the following line in the "esriDynamicMapServiceLayer" directive:

    var layer = new ArcGISDynamicMapServiceLayer($attrs.url, layerOptions);

to

    var layer = new ArcGISDynamicMapServiceLayer($scope.url, layerOptions);

Is this the best way to fix the problem?

**Comment by tomwayson** [comment]
Thanks @Kollibri 

I was just writing to tell you that it looks like your copy of angular-esri-map.js is not the latest, which [reads the URL off the scope](https://github.com/Esri/angular-esri-map/blob/master/src/directives/esriDynamicMapServiceLayer.js#L148). Updating to master should fix this, or you can leave the patch you have until Beta 6 is released.

**Comment by Kollibri** [comment]
Ok thanks!  =)
