### ISSUE TITLE
TOC?

### ISSUE THREAD

**Issue by Kollibri** [Esri/angular-esri-map#128]
Is there an interest in adding a TOC (table of contents) with the legend and the layers on/off functionality in one directive?

I have got something working in my local branch and would like to make a pull request for it if there is interest.  I had to make a minor change to the "esriDynamicMapService" directive to take an additional attribute, but other than that it is self contained in a new "esriToc" directive.

Even if you don't want to use it, I would be glad of any feedback you have on it.  If there is a better way to implement it, etc.

**Comment by tomwayson** [comment]
I think there's always a demand for that kind of TOC/layers widget, but I don't know if it should be included w/in this library - I'm trying to stick to a subset of what is in the JSAPI. Ideally you could create your own standalone angular module that depends on this one that implements the TOC/legend directive. If that module needs a change to the esriDynamicMapService you could PR just that change here and I can figure out what's the best way to make sure your module gets what it needs from this one's API.

**Comment by Kollibri** [comment]
I figured out how to use the additional "layer-options" to set the variable I needed instead of modifying the attributes on the layer directly.  So there are no changes needed to make this TOC work.  I will work on making a separate repository for this as a plugin.  Do you have a recommended name for the repository/plugin?  I was going to do angular-esri-map-toc, unless you object.

**Comment by tomwayson** [comment]
angular-esri-map-toc sounds good.

w/r/t CORS services, I don't know off hand. I just use trial and error. Did you try the map service in the legend example?

**Comment by Kollibri** [comment]
The legend example uses feature layers instead of dynamic map service. We don't really use feature layers here at the office so I'm not familiar with them. I know that my toc directive is expecting a dynamic map service directive so it won't work with the esriFeatureLayer directive. There is another third party dojo digit that is similar... I will check and see what map services it is using.

**Comment by Kollibri** [comment]
I found a map service at http://sampleserver5.arcgisonline.com/arcgis/rest/services/NetworkAnalysis/SanDiego/MapServer that works well for the TOC (CORS enabled and has nested layers). I will work on creating a repository for the toc plugin and update here when it is done.

**Comment by Kollibri** [comment]
I have my first attempt at a Bower component that can be used as a plugin for angular-esri-map bower component done.
https://github.com/Kollibri/angular-esri-map-toc

I still think of myself as an angular newb so would love to have any suggestions regarding the actual directive itself.

**Comment by tomwayson** [comment]
@Kollibri this is awesome!

I haven't had a chance to review yet, but will definitely do so soon.

**Comment by jwasilgeo** [comment]
Hi @Kollibri we definitely let this one drag out, sorry about that!  We have been super swamped for ages.  BTW it was nice to meet you at Dev Summit.

I think this is a neat directive!  The only operational issue I've come across (at least in your demo) is a discrepancy between group layers ("Government") and the visibility of its children ("State Capitol", "Post Office").  To reproduce:

1. Expand the children to get to "State Capitol" (id 14).
2. Toggle it off.  No change in visibility on the map, but the layer id has indeed been removed from the console log array.
3. Toggle the parent "Government" (id 13) off and then on again.
4. Now, toggling the child "State Capitol" works, and the only major difference is that the "Government" id value of 13 never appears in the console array.

**Comment by Kollibri** [comment]
Hi @jwasilge was really nice meeting you at the Dev Summit as well!

I actually haven't done much work with this directive.  I knew it had some problems but didn't come back to it.

We've actually been using the ESRI JS API 4 these last couple months and noticed that there are references to a "table of contents" in the documentation, but there doesn't appear to be any actual "table of contents" widget.

For example, the layers all have a "listMode" property that says: "Indicates how the layer should display in the table of contents." but that's the only place where "table of contents" is mentioned.

Do you, or @tomwayson know what "table of contents" is referring to in this instance?

As for this issue, I think it can be closed.  I'm not sure if I'm going to go back and get this directive working given that I've moved on to JS API 4.

**Comment by jwasilgeo** [comment]
@Kollibri glad to hear you are getting to use JSAPI 4.  I don't know myself about the table of contents, but that is interesting and worth paying attention to for future versions of JSAPI 4.x...
