### ISSUE TITLE
InfoTemplate Content Scenario

### ISSUE THREAD

**Issue by bwcoleman18** [Esri/angular-esri-map#131]
For the InfoTemplate, do you think it would be a good idea to allow for the content to be set from the directive instead of the element's html (angular-esri-map.js line 726 sets from html)?

<b>My Problem...</b>
I was trying to wrap the esri-dynamic-map-layer directive in a ng-repeat with content being set in there, but it wasn't rendering properly.  I am looking to load things dynamically via JSON in order to make a template where you just drop in a JSON config, and it renders.

e.g.
 `<esri-map id="map" center="setup.map.center" zoom="setup.map.zoom" basemap="{{setup.map.basemap}}">
<esri-dynamic-map-service-layer ng-repeat="layer in setup.layers" title="{{layer.Name}}" visible="{{layer.IsVisible}}" visible-layers="{{layer.ID}}" opacity="{{layer.Opacity}}" url="{{layer.URL}}"><span ng-if="layer.showIdentify" ><esri-info-template layer-id="{{layer.ID}}" title="<b>{{layer.Identify.Title}}</b>" >{{layer.Identify.Content}}</esri-info-template></span></esri-dynamic-map-service-layer></esri-map>`

I kept getting `{{layer.Identify.Content}}` showing inside my infoTemplate instead of the info I had set there.  Originally, I tried using something like:
`<span ng-repeat="field in layer.Identify.Fields">{{field.Display}}: ${{{field.FieldName}}}</span>` but I came up with similar results.

Where I would just use the `ng-repeat` to loop through my fields I want to display, but I came up with the a similar result.

<b>My Quick Fix</b>
I was able to get it to work but changed a few things.  I changed the `<esri-info-template>` to have another attribute `content` on there so it ended up being `content="{{layer.Identify.Content}}`, which meant I needed to modify the the angular-esri-map.js file around line 738 to:
`if (dynamicMapServiceLayerController) {
                        if (attrs.content) {
                            content = attrs.content; //attribute I set in the markup
                        }
                        dynamicMapServiceLayerController.setInfoTemplate(attrs.layerId, {
                            title: attrs.title,
                            content: content
                        });
                    }`

My content would be something like:
`"Council Ward: ${PRECINCT}<br />Canopy Acres: ${CANOPY_ACR}<br />"`
That allowed me to use my config JSON, loop, and properly set up my infoTemplates.

<b>What I'd Like to Know</b>
I am curious if there is a better way to do this, or if the idea of using `ng-repeat` to pull in layer info from some config somewhere was considered.  I find that the angular version of this allows me to make config files into of JS files.  Eventually, my goal is to feed the JSON in from a database instead of a .json file, so I can have easier webmap deployment.

**Comment by tomwayson** [comment]
@bwcoleman18 

The idea of using ng-repeat to add layers from a config has definitely been considered. See:

**Comment by bwcoleman18** [comment]
@tomwayson  

Thanks for the information.  I think utilizing the `layer-options` style would be much easier.  I think it is a cleaner and more uniform approach to configuring via JSON.
