### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#139]
We should have e2e sepcs for each test page.  After PR #137, we will need to add:
- ~~custom-directive~~
- legend
- ~~other-esri-modules~~

**Comment by tomwayson** [comment]
I'm not sure about custom-directive - basically the only part of this library that that page uses is esri.core, and I'm assuming that's thoroughly covered by the other tests.

Same w/ other-esri-modules. I don't know if that uses any part of the module that is not covered by other tests.

I didn't realize that we didn't have a test for legend. We should definitely add that.

**Comment by jwasil** [comment]
Good points above
