### ISSUE TITLE
placing point (lng, lat) on the map

### ISSUE THREAD

**Issue by snobrdinrtiste** [Esri/angular-esri-map#143]
Is there a way to add a point with a picturemarkersymbol onto the map? like a pin after geocoding an address?  or can I use the regular ArcGIS Javascript API way of doing this?

**Comment by snobrdinrtiste** [comment]
nevermind :) ... found it

**Comment by randhawp** [comment]
Can you place share it as there is no example on it

**Comment by snobrdinrtiste** [comment]
I will post an example on Thursday when I get back into work since tomorrow is Veteran's day.

**Comment by jwasil** [comment]
You could borrow some ideas from this example on how to bring in any ArcGIS API for JavaScript modules you'd like to work with:  http://esri.github.io/angular-esri-map/#/examples/other-esri-modules

**Comment by snobrdinrtiste** [comment]
sorry forgot about sharing code... lol
here's what i have ...

$http.get("https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=" + singleaddress)
                    .success(function (response) {
                        var mylat = response.results[0].geometry.location.lat;
                        var mylng = response.results[0].geometry.location.lng;
                    
                        var mypoint = new Point(mylng, mylat);
                        var symbol = new PictureMarkerSymbol($scope.serviceBase + 'images/red-pin.png', 17, 32);
                        var graphic = new Graphic(mypoint, symbol);
                        map.graphics.add(graphic);

                        $scope.map.center.lat = mylat;
                        $scope.map.center.lng = mylng;
                        $scope.map.zoom = 15;
                    })
                    .error(function (response) {
                        SweetAlert.swal("Google Maps API Error!", "Error geocoding address!\nServer response: " + response, "error");
                    });

**Comment by randhawp** [comment]
Thank you. Appreciated.

**Comment by tomwayson** [comment]
@jwasil - looks like warce really need to add a geocoding example :wink:
