### ISSUE TITLE
Consider adding a single-module synchronous require to esriLoader

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#144]
Checkout out [Ken's answer to this SO question](http://stackoverflow.com/a/33620918/656010).

There are times when I want to be able to just use a module that I know is included in the build (like esri/config) in something like a module's `run()` that does not support async code. I think esri/basemap is included in the CDN builds too, so that means we could turn [`esriMapUtils.addCustomBasemap()`](https://github.com/Esri/angular-esri-map/blob/master/src/core/esriMapUtils.js#L20) into a synchronous function, and again, make it something that can be configured in the module's `.run()` in addition to a route's resolve.

Name could be `esriLoader.requireSync()`?

**Comment by jwasil** [comment]
Interesting and :cool: idea. I vote for running with `esriLoader.requireSync()`.

**Comment by tomwayson** [comment]
This didn't really work. I got a "undefinedModule" error for all modules that I tried to load this way (esri/config, esri/basemaps, esri/map). I blame Dojo.

Closing, as this is not worth our time right now.

**Comment by jwasil** [comment]
:cry: Thanks for giving it a shot, though.
