### ISSUE TITLE
3d globe / SceneView

### ISSUE THREAD

**Issue by dbroadhurst** [Esri/angular-esri-map#148]
Is it possible to display a 3d globe wth angular-esri-map? It looks like it would require SceneView but just wanted to check before I started to implement.

**Comment by dbroadhurst** [comment]
Looks like this will be part of a larger effort to upgrade to v4 API

**Comment by jwasil** [comment]
@dbroadhurst angular-esri-map is [focused on](https://github.com/Esri/angular-esri-map#dependencies) working with v**3**.11+ of the ArcGIS API for JavaScript.  [v4](https://developers.arcgis.com/javascript/beta/) itself will introduce a lot of underlying changes, and won't be directly part of this project.  I'll let @tomwayson have the final word on this though if there's anything else to add.

**Comment by tomwayson** [comment]
Actually that *will* be part of this project, just not until v2. We are very close to a v1 release. Will start on v2 shortly thereafter. I will probably be playing with JSAPI 4 beta and angular very soon and will link to those experiments from this issue.

**Comment by jwasil** [comment]
@dbroadhurst sorry for the confusion above in my earlier comment

**Comment by tomwayson** [comment]
I forgot to update this issue w/ the link to the plunk I started w/ JSAPI 4.0 beta (2) and Angular:

http://plnkr.co/edit/h7P76Gxw3Qckd2zvqGRq?p=info

And this one shows JSAPI 4.0 beta 3 with a custom widget directive

http://plnkr.co/edit/2QbrzR6shryLbE72So7n?p=preview

The latter will become the basis for version 2 of this library.

**Comment by MarcBate** [comment]
looks good so far!

**Comment by tomwayson** [comment]
Thanks @MarcBate.

FYI - you can start playing w/ this by checking out the [v2-beta-1 branch](https://github.com/Esri/angular-esri-map/tree/v2-beta-1).

Also, here's the roadmap: 
https://github.com/Esri/angular-esri-map/milestones/v2-beta.1
https://github.com/Esri/angular-esri-map/milestones/v2-beta.2

As always, issues or PRs are welcome.

**Comment by MarcBate** [comment]
Will v2 make it easier for developers to add a 2D/3D toggle to switch views for currently loaded layers?

**Comment by tomwayson** [comment]
@MarcBate 

v2 is what will make it *possible* to show 3D at all, since v1 is not compatible w/ JSAPI v4.x. 

Our goal is, if it's possible in the JSAPI outside of Angular, this repo should make it easier in Angular. 

I think you're asking if it will be easy to toggle between a 2D and 3D views of a map with currently loaded layers. I don't see any examples of switching between 2D/3D views in the beta 3 samples, but if you created an example of it (in a plunker or fiddle) then we should be able to help guide you how to make it work in Angular.

**Comment by tomwayson** [comment]
Closing this as [v2.0.0-beta.1](https://github.com/Esri/angular-esri-map/releases/tag/v2.0.0-beta.1) based on JSAPI v4-beta.3 has been released and inlcudes (beta) support for SceneViews.
