### ISSUE TITLE
Unit tests for controllers and/or directives?

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#149]
There are a few functions in the controllers that could be easily unit tested (basically everything outside of the the `bindToXxxEvents` functions), but I'm not sure if it's worth it, or if those should be covered by tests of directives.

Not even sure if/how to test directives, especially w/ such good e2e coverage.

Suggestions welcome here.

**Comment by jwasil** [comment]
I've been mulling over this and still don't have a clear Y/N in my mind. I'm thinking I don't mind just giving some tests going an informal shot to see what the LoE is here.

**Comment by jwasil** [comment]
Starting to mess around here on a new branch: https://github.com/Esri/angular-esri-map/commit/4585a21fd8cfccf8b7b6c7e418dcdda7b84daaa5  Starting to get some code coverage for one of our controllers!

**Comment by tomwayson** [comment]
Unit tests for services, e2e tests for directives.

**Comment by jwasilgeo** [comment]
We can probably delete this branch, which I haven't been on in ages.

https://github.com/Esri/angular-esri-map/compare/controller-unit-tests

Your call.

**Comment by tomwayson** [comment]
Done.
