### ISSUE TITLE
Integrating label layer feature in feature layer service?

### ISSUE THREAD

**Issue by jmrroy** [Esri/angular-esri-map#152]
Hi,
Do you plan to integrate label layer in angular-esri-map? 
It is a very important feature, when using features layer! I unfortunately failed to use the label layer in the way you show in your "other esri modules example".
Maybe can someone show it in a short example?

**Comment by tomwayson** [comment]
@jmrroy let me know if this works for you:

http://plnkr.co/edit/z9UWPFUw4L1roccShxrS?p=preview

**Comment by jmrroy** [comment]
@tomwayson It works!
Thank you very much for your help!

But It works only once, after reloading a route I have an error : 
TypeError: Cannot read property 'addLayer' of null
    at angular-esri-map.js:111
    at ha (init.js:22)
    at init.js:15
    at ia (init.js:23)
    at La (init.js:15)
    at r (init.js:5)
    at Object.requireModule [as require] (angular-esri-map.js:105)
    at $scope.addLabels (carriereDet2.js:74)
    at angular-esri-map.js:1043

PS: nice job to you and your team for the RC1 with the docs.

**Comment by tomwayson** [comment]
@jmrroy 

Thanks for the kudos on the docs!

Any chance you can fork the above plunker and modify it to include a router, or create your own, that reproduces the problem?

**Comment by jmrroy** [comment]
@tomwayson 
Yes, here is a plunker with ui-router : http://plnkr.co/edit/hDlIvOJPDKA03yjzkm5s?p=preview

**Comment by tomwayson** [comment]
@jmrroy 

Thanks for taking the time to put together that sample. I've got it working here:

http://plnkr.co/edit/nbWckSXroVMvUglohXaP?p=preview

The second time around the layer load event fires before the layer is added to the map, so it's safer to use a one time handler for the `update-end` event which fires after the layer has been added to the map and fetches data.

Let me know if this works for you.

**Comment by jmrroy** [comment]
Hi @tomwayson,
It works for me. Thank you!
How can I do to use a load event on two features layer that require the same Esri module?
Put the esriLoader.require on the map load event to be able to use the module on the load feature event?

**Comment by tomwayson** [comment]
Yes, you could use the map directive's load event to require the module and get a reference to the map object and the layers that have been added by any feature layer directives. This is actually a simpler way to accomplish the above:

http://plnkr.co/edit/nbWckSXroVMvUglohXaP?p=preview

I actually did not expect that to work, but it does. I did not think that the tree layer would have been added to the map at that point, and that you would have had to handle the map object's [layers-add-result](https://developers.arcgis.com/javascript/jsapi/map-amd.html#event-layers-add-result) event to get direct references to the layers.

**Comment by jmrroy** [comment]
@tomwayson 
Great! Very nice solution. I can  now label multiple layers.
Thanks again!

**Comment by tomwayson** [comment]
Glad that worked for you. Closing this issue.
