### ISSUE TITLE
Documentation landing page should not be blank

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#153]
This looks broken:

http://esri.github.io/angular-esri-map/docs/#/api

I've tried dropping .ngdoc files all over the damn place, and I can't get anything to show up there.

As a temp fix, I'm going to set links to point to the esriMap page, but there has to be a way to show some content on that page.

**Comment by jwasil** [comment]
Agreed that it gives the appearance of something being not quite right, and agreed that a good temp fix is to just point to esriMap documentation page.  I'll help dig around and see if there's anything else that might work for us.

**Comment by jwasil** [comment]
Couple things here...this might be a solution, currently fighting with getting it to work:  https://github.com/nikhilmodak/gulp-ngdocs/issues/37#issuecomment-96225676

Would be awesome if the 2 **modules** could actually be documented, that is **esri.map** and **esri.core** but using `@ngdoc overview` doesn't seem to do anything.  https://github.com/nikhilmodak/gulp-ngdocs/issues/20#issuecomment-72613940
