### ISSUE TITLE
esriLoader to accept option for dojoConfig

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#167]
I'd like to have the ability to define and set the `dojoConfig` options prior to loading the JSAPI.  Specifically, I'm interested in the [`packages` property](https://dojotoolkit.org/documentation/tutorials/1.10/dojo_config/index.html#loader-configuration), to be able to include modules that aren't part of the core JSAPI.

My thoughts are this could be done in a previous `script` element and set the `dojoConfig` variable, or perhaps it may be more streamlined to just add an additional attribute to the single `script` element and do something like:
`script.setAttribute('data-dojo-config', 'packages:[...], andWhateverElseIsPassedIn')`
However, if getting the path correct proves to require some hand-holding and we want [some regex](https://github.com/jwasil/angular-esri-playground/blob/master/index.html#L75), perhaps the first option would be better?

If we need an example to illustrate the point of this, we could create something that makes use of the _Esri/cluster-layer-js_ repo.

Thoughts?  Any arguments against adding this?

**Comment by tomwayson** [comment]
Generally we'd want to minimize the amount of modules we load via nested require blocks, so anything that can be loaded w/o the esriLoader should be. However, you do present a valid use case (a module that depends on other JSAPI modules).

That said, I don't see why you couldn't just handle that by adding a script that modifies the `dojoConfig` global prior to loading the JSAPI. That's how I do it, even in my Dojo projects.

**Comment by jwasil** [comment]
Yeah, agreed. Let's let folks just add their own script tag for `dojoConfig` in those cases when someone is adding in another local module in addition to JSAPI.
