### ISSUE TITLE
"angular-esri-map.js" can not be found in the downloaded code

### ISSUE THREAD

**Issue by Shawn-Fan** [Esri/angular-esri-map#169]
Under the project Root folder, there should be one file "/lib/angular-esri-map.js" used by "index.html", But It can be found in the "http://esri.github.io/angular-esri-map/#/examples/simple-map" code.

**Comment by tomwayson** [comment]
@Shawn-Fan thank you for opening an issue.

I just want to make sure I understand what you mean by "downloaded code". The "angular-esri-map.js" file is generated by our gulp build scripts and is not included the the source code. So it will not be included when you clone or click the [download link](https://github.com/Esri/angular-esri-map/archive/master.zip) from the repo's home page. You will have to follow the [development instructions](https://github.com/Esri/angular-esri-map#development-instructions) to build that file from the source.

However, the our [releases](https://github.com/Esri/angular-esri-map/releases/tag/v1.0.0-rc.2) include a "dist" folder which contains the generated files. That should be included in bower installs as well.

There is a known issue #154 causing the generated files to not be included in the published npm package.

Please let me know if any of that is inaccurate or unclear.

**Comment by Shawn-Fan** [comment]
Thank you. It works

**Comment by randhawp** [comment]
Can confirm that bower or npn both work and the required files are generated.

**Comment by Shawn-Fan** [comment]
I downloaded code yesterday, unzip it and can not found "angular-esri-map.js" which should be under "angular-esri-map-master/site/lib/"folder. I grabbed it from "http://esri.github.io/angular-esri-map/#/examples" and it worked. Today, I found "angular-esri-map.js" in under"https://github.com/Esri/angular-esri-map/releases" ==>"angular-esri-map-v1.0.0-rc.2.zip". You can try if it works by npm/bower.

Date: Thu, 3 Dec 2015 09:22:55 -0800

**Comment by tomwayson** [comment]
Thank you both for confirming. I'm closing this issue.
