### ISSUE TITLE
Fix hidden SnippetsCtrl in examples site page

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#170]
The SnippetsCtrl depends on the `leftNavStyle` binding, which worked when the index.html page had only the ExamplesCtrl and then SnippetsCtrl.  It appears that the nesting is slightly off [here](https://github.com/Esri/angular-esri-map/blob/master/site/index.html#L75) under PatternsCtrl, since SnippetsCtrl `leftNavStyle` value should line up with parent `leftNavStyle` in ExamplesCtrl.  The effect is that the snippets tabs are always hidden when browsing example pages.

**Comment by tomwayson** [comment]
thanks for finding and fixing that @jwasil!
