### ISSUE TITLE
FeatureLayer construction via a feature collection object

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#172]
Comes out of conversation from #171. Let's see what it might take to allow passing in a feature collection object to the esriFeatureLayer directive, as an alternative to an AGS layer url.

**Comment by jwasil** [comment]
I think this is going to be a bigger-sized task if we want to follow through for JSAPI 3.x.  Setting up the `featureCollection.layerDefinition` is straightforward, but providing a flexible and easy to use API to wrap around different geometry types for the `featureCollection.featureSet` I think will take some fancy footwork in **esriLayerUtils**.  I wonder if this might expand our footprint a bit?  I've been playing around with just trying to construct Graphics from JSON for the items in the `featureSet` and haven't had the best of luck so far.  Maybe we should chat more and revisit this?

**Comment by tomwayson** [comment]
yeah, let's table this for now.
