### ISSUE TITLE
Point bower main to minified source code

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#174]
@tomwayson, what do you think about this?  Can we get [bower.json main](https://github.com/Esri/angular-esri-map/blob/v1.0.0-rc.2/bower.json#L14) to point to the **angular-esri-map._min.js_** before the next tagged release?  I think this would help solve an oddity I'm seeing when trying to minify and concat vendor dependencies for another app.

**Comment by tomwayson** [comment]
@jwasil 

I'd really rather not point bower at .min.js as it just does not seem to [be](https://github.com/formly-js/angular-formly/blob/master/bower.json#L10) [the](https://github.com/angular-ui/ui-router/blob/master/bower.json#L5) [norm](https://github.com/angular-ui/angular-google-maps/blob/master/bower.json#L4).

It's hard to tell if there are issues w/ the distribution files, or with the build system you're using. Until we hear that others are having problems, I'm inclined to leave bower's main as is for now.

**Comment by jwasil** [comment]
@tomwayson thank you for your help in troubleshooting this with me.  I followed your suggestion to use a [bower overrides](https://www.npmjs.com/package/main-bower-files#main) and that helped solve my issue in another app.  I understand we want to keep an eye on this for the future, but I'll leave it up to you now if you want to close this.  Thanks.

**Comment by tomwayson** [comment]
@jwasil would you mind posting the actual overrides section that you added to your bower.json file?

Beyond that I'd say let's close this for now but keep an eye out in case others have the same issue.

**Comment by jwasil** [comment]
Absolutely.
```javascript
"overrides": {
  "angular-esri-map": {
    "main": "dist/angular-esri-map.min.js"
  }
 }
```

I suggest the following approach if only needing something found in the **esri.core** module (for example if your app only uses the **esriLoader**):
```javascript
"overrides": {
  "angular-esri-map": {
    "main": "dist/angular-esri-core.min.js"
  }
 }
```

For the development project in question which led to this solution, I happened to fall into the latter situation.

**Comment by tomwayson** [comment]
Nice tip on using overrides to load the core module only if needed!
