### ISSUE TITLE
Question on "Angular-esri-map" library

### ISSUE THREAD

**Issue by Shawn-Fan** [Esri/angular-esri-map#175]
"Angular-esri-map" is an very nice library developed by Angular1 based on JSAPI 3.14,  Some functions like displaying map, legend, feature layer,... cab be used to develop web maps. I am wondering if you have plan to add more functions in "Angular-esri-map"? Angular 2 is around the corner, will you continue to  work on it or migrate to NG2?

**Comment by tomwayson** [comment]
@Shawn-Fan I'm glad you like the repo.

Right now our roadmap is looks like:

v1.0.0 - Angular 1.x w/ JSAPI 3.x
v2.0.0 - Angular 1.x w/ JSAPI 4.x
v3.0.0 - Angular 2.x w/ JSAPI 4.x

I don't have a concrete timeline for any of those. We would have released 1.0.0 last week if we weren't considering #173.

Beyond possible support for Vector tiles, we are definitely not going to add any features for v1. Instead we are really focused on [making it easy for developers to extend the directives we've created](http://esri.github.io/angular-esri-map/#/patterns). If there's anything we can do to make that easier, we welcome suggestions here.
