### ISSUE TITLE
error with the map when using multiple tabs

### ISSUE THREAD

**Issue by jccartwright** [Esri/angular-esri-map#176]
I'm getting a "Error: [$rootScope:inprog] $apply already in progress" error when switching tabs to one which contains the map.  The error is related to the $scope.apply where I register the activateDrawTool, e.g.
                    $scope.$apply(function () {
                        $scope.activateDrawTool = activateDrawTool;
                    });

This based on the http://esri.github.io/angular-esri-map/#/examples/other-esri-modules example.

Any help would be much appreciated!

--john

**Comment by tomwayson** [comment]
@jccartwright which tabs are you using? UI-Bootstrap? 

any chance you can post your code to a fiddle/bin/plunker?

**Comment by jccartwright** [comment]
Thanks for your reply Tom.  They’re really Angular views estivated with tabs.  It’s based on the yeoman angular  generator.

The code is in github at https://github.com/jccartwright/nos-products/ 

index_advanced.html is the page w/ multiple views

—john

**Comment by jwasil** [comment]
@jccartwright I've also noticed that manually applying scope can sometimes be called when an angular digest/apply is actually already in progress.  I'm curious what will happen if you can try the following: can you wrap the scope apply that you think is causing this error in a conditional check (in order to only apply scope if it isn't already in progress)?

```javascript
if ($scope.$root.$$phase !== '$apply' && $scope.$root.$$phase !== '$digest') {
  $scope.$apply();
}
```

**Comment by tomwayson** [comment]
I can confirm that ^^^ works, See below

```js
                    // set the active tool once a button is clicked
                    // apply this function binding to scope since it is outside of the digest cycle
                    if ($scope.$root.$$phase !== '$apply' && $scope.$root.$$phase !== '$digest') {
                        $scope.$apply(function () {
                            $scope.activateDrawTool = activateDrawTool;
                            $scope.clearGraphics = clearGraphics;
                        });
                    } else {
                        $scope.activateDrawTool = activateDrawTool;
                        $scope.clearGraphics = clearGraphics;
                    }
```

To me though, that feels like a (dirty) bandaid to treat the symptom, not the cause. Looks like you're using ngRoute to switch between views - this is the same thing we're doing in the [example application](http://esri.github.io/angular-esri-map) and we don't have this kind of issue, so there's something else going on in your app. Hopefully the above temp fix can get you through until you are able to get to root causes.

Thanks @jwasil!

**Comment by jccartwright** [comment]
Thanks to you both.  The suggested workaround does work for me but I haven't been able to yet understand how my app differs from your example in this respect.  I'll keep looking...

**Comment by tomwayson** [comment]
@jccartwright no problem. Looks like a useful application BTW - would be glad to hear if/when you launch it (if it's public facing).
