### ISSUE TITLE
remove derived files from repo and add them to .gitignore

### ISSUE THREAD

**Issue by jabadia** [Esri/angular-esri-map#18]
files generated by gulp (like angular-esri-map.js and angular-esri-map.min.js) should not be tracked by git, as they can be recreated locally by gulp at any time

having them in the repo makes it more difficult to merge and rebase branches, as you have to solve the same code conflicts in several files

I understand that they need to be in the gh-pages branch so that the online demo works... we need to automate that in the gulp build process

what do you think?

**Comment by tomwayson** [comment]
Looks like Esri leaflet has moved on from grunt-releasable to using [custom publish/build scripts](https://github.com/Esri/esri-leaflet/tree/master/scripts) with [gh-release](https://www.npmjs.com/package/gh-release). gh-release looks pretty :fire:, and seems like it could be useful in solving this issue.

**Comment by tomwayson** [comment]
Resolved (finally) by 080f5a077f00a567d715ea90af60ca4ad9fcdca1
