### ISSUE TITLE
Unable to update map height

### ISSUE THREAD

**Issue by avitter** [Esri/angular-esri-map#188]
From what i can tell of the esri-map directive, there is no way to adjust the height of a map (Ex. have the map take entire height of containing element).  I solved the issue by updating the esri-map directive to assume 100% height/width of parent element:

esri-map directive - complile function: when appending new div
add style="height:100%; width:100%" to the div

If there is already a way to adjust the map height, please let me know or else you might consider updating the esri-map directive in a similar manor.

**Comment by tomwayson** [comment]
You should be able to set the height by applying a style to map's div. See:

http://plnkr.co/edit/zOOFW2HnDoSySWrmZRsv?p=preview

**Comment by avitter** [comment]
Ah … that makes sense.  However, that only works because you are applying style based on div’s id.  The id gets transferred to the div that gets appended inside the directive’s div in the compile function.  This works for a vast majority of situations.  However, what if you have multiple maps on a page?  In that scenario you would have to have different IDs for each map and therefore know the ids of all maps for implementing the css styles.  My only point is that it would be nice to apply style to the map without having to use id selectors.  I’d like to be able to apply style to all maps with a single map class.

 

Thanks again for the reply.

**Comment by tomwayson** [comment]
Actually, you _can_ set the height  w/o ids like so:

```css
          .map {
            height: 600px;
          }
```

You can use that, or any other valid CSS selector, to update all the maps on your page.

I've updated the plunker accordingly. If this works for you, would you mind closing the issue? Thanks!

**Comment by avitter** [comment]
Ha ... I had tried that but of course had a stupid typo.  Thanks so much for the quick responses.

**Comment by tomwayson** [comment]
Great, glad that helped.

Also, one thing to keep in mind is that if you are trying to test out your styles with Developer Tools, anything that changes the size of the div that contains the map, may not _look_ like it's working, because you may have to tell the map object to resize itself (by calling its `.resize()` method).
