### ISSUE TITLE
More InfoTemplate flexibility

### ISSUE THREAD

**Issue by collinforrester** [Esri/angular-esri-map#189]
First off,  great library.  Makes me happy to see companies not only put some effort into their javascript libs but also open source them like this.

My issue is probably more because of my lack of understanding than an issue with the library.

What I'm trying to do is use the built in InfoTemplate to show all attributes of the selected point.  The [InfoTemplate docs](https://developers.arcgis.com/javascript/jsapi/infotemplate-amd.html) say it is possible by specifying content as `${*}`.  

That didn't work for me so I ended up editing the source of this library to evaluate the angular expression I had set in the template: `<div class='demographicInfoContent'>{{selectedLayer.content}}</div>` where `content` is nothing more than some HTML that I've built by hand (where I finally add `<td>${field.alias}</td><td>\$\{${field.name}\}</td>`).

The difficulty for me is that I don't know ahead of time what the fields I should show in the template are and this is my poor man's way of using the built in wildcard.

Is there a better way or am I off?

**Comment by jwasil** [comment]
@collinforrester thank you for the great feedback!

If you are using the **esri-info-template** directive in your html to establish the InfoTemplate, can you make sure there is no whitespace in the innerHTML if you are using `${*}`?  For example:

`<esri-info-template layer-id="0" title="abcxyz">${*}</esri-info-template>`

**Comment by collinforrester** [comment]
That was the issue.  I think the extra div that I had in there was throwing things off.  Thanks!
