### ISSUE TITLE
For v2 drop esri.core util services and either drop registry, or add support for it to directives

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#191]
So far [esriMapViewUtils](https://github.com/Esri/angular-esri-map/blob/v2-beta-1/src/core/esriMapViewUtils.js#L29-L35) and [esriSceneViewUtils](https://github.com/Esri/angular-esri-map/blob/v2-beta-1/src/core/esriSceneViewUtils.js#L29-L36) are such thin wrappers around esriLoader (thanks to @ycabon's [accessors](https://ycabon.github.io/presentations/2015-berlin-js-api4-whats-new/#/14)) that I honestly think we should get rid of thes utility services - or at the very least incorporate them into a single service (esriViewUtils).

Furthermore, as far as the registry goes, do we need it? Unless there's a situation where the registry offers an advantage over binding to the directive events, we might consider dropping it. Otherwise, we'll have to add support for register-as to both the esriMapView and esriSceneView directives.

Less is more.

**Comment by jwasil** [comment]
My :thought_balloon:s:
- view utils: agreed, blast `em or concat them down to one esriViewUtils
- registry: I see what you're getting at, but it might be too early to tell.  So long as users can, or know how to (Patterns documentation page?), pass around reference to views, maps, etc. in a more complex Angular application, (e.g. using `$q` deferreds in a shared factory), I agree that less is more.

**Comment by tomwayson** [comment]
Great. I say let's get rid of them all (utils and registry) for now. If needed, we can add the registry back.
