### ISSUE TITLE
v2 docs pages style fixes

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#192]
Currently the v2 docs pages have some style issues. The left nav isn't tall enough, so the code snippets slide to the left. The map on the home button example is very short.

**Comment by jwasil** [comment]
Code snippets: just from briefly messing around with the `<div ng-controller="SnippetsCtrl"...` element, it seems like a quick little `float: right;` seems to fix it.

**Comment by tomwayson** [comment]
Go for it!
