### ISSUE TITLE
Which JSAPI 4 sample pages should we include in v2 tests/docs?

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#194]
Create an issue for each of these that we want to include. Some ideas:

- [Pop ups](https://developers.arcgis.com/javascript/beta/sample-code/get-started-popup/index.html)
- [Bookmarks](https://developers.arcgis.com/javascript/beta/sample-code/webscene-slides/index.html)
- [Extrude](https://developers.arcgis.com/javascript/beta/sample-code/polygon-extrusion-3d/index.html)
- [Elevation](https://developers.arcgis.com/javascript/beta/sample-code/scene-toggle-elevation/index.html)
- [Search](https://developers.arcgis.com/javascript/beta/sample-code/widgets-search-2d/index.html)

I don't foresee any of those requiring any new directives.

@jwasil would love your input here.

Also, I have no idea what this [chaining promises sample](https://developers.arcgis.com/javascript/beta/sample-code/chaining-promises/index.html) is trying to demonstrate, but it _seems_ like something we ought to make sure we can do w/in a test page.

**Comment by jwasil** [comment]
@tomwayson your proposed list sounds great to me.  That chaining promises sample could lead to an interesting code snippet; neat that it uses GeometryEngine as well.  What do you think about also throwing in:
- [Geodesic buffers](https://developers.arcgis.com/javascript/beta/sample-code/ge-geodesicbuffer/index.html) (I'm all about giving shout-outs to the GeometryEngine)
- [Vector tiles](https://developers.arcgis.com/javascript/beta/sample-code/layers-vectortilelayer/index.html) (to keep continuity with the v1 docs examples)?

**Comment by tomwayson** [comment]
Both of those look like good suggestions, esp the geodesic buffers.

**Comment by bsvensson** [comment]
@tomwayson - We expect that many 3.x people aren't yet familiar with promises. Thus both a guide topic [Working with promises](https://developers.arcgis.com/javascript/beta/guide/working-with-promises/index.html) and [the chaining promises sample](https://developers.arcgis.com/javascript/beta/sample-code/chaining-promises/index.html) sample.  I'm not sure how that translates to angular-esri-map folks...

**Comment by jwasil** [comment]
@bsvensson thanks for the info and links!

**Comment by jwasil** [comment]
Not part of JSAPI v4 examples, but let's also consider:
- adding a separate example page to show how a dev can wire up live binding between JSAPI properties and Angular with a little optional help from `$scope` (stemming from #209)

**Comment by tomwayson** [comment]
resolved in #223
