### ISSUE TITLE
include the home button directive under src

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#195]
Move the home button example move under src In other words, we should ship at least one example directive that shows how to create a native angular that uses the widget view models.

Need to figure out the src folder structure too - src/map doesn't make much sense when all we are shipping is map view, scene view, and home button.

The [locator button](https://developers.arcgis.com/javascript/beta/sample-code/widgets-locate/index.html) or [basemap toggle](https://developers.arcgis.com/javascript/beta/sample-code/widgets-basemaptoggle-2d/index.html) could be included in a later beta of this repo.

**Comment by jwasil** [comment]
Note to assignee:
Once #191 and this settle, also make sure to add inline documentation for **esriMapView**, **esriSceneView**, home button, etc.

**Comment by jwasil** [comment]
@tomwayson for folder structure and naming of the **esri.*** modules, what about something like:
```
src
 ├── core
 ├── directives (all views and widgets go here)
```
or split it out, but Angular folks will be scared of the word **widget**:
```
src
 ├── core
 ├── views
 ├── widgets
```
or?

**Comment by tomwayson** [comment]
```
src
 ├── core
 ├── directives (all views and widgets go here)
```

works for me.

**Comment by jwasil** [comment]
Just for the paper trail, we reverted back to the original structure in PR #198
```
src
 ├── core
 ├── map
```
