### ISSUE TITLE
Should the demo and docs site be extended to support major releases?

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#197]
Meaning, should we expand the gh-pages site to allow for different examples and API docs content for v1, v2, and v3 of this repo?  If so, how shall we go about doing it?  I can envision a simple `<select>` element to choose the version, but then managing the routes, content, different angular-esri-map src code, etc. doesn't immediately present itself as very straightforward.  Thoughts, @tomwayson?  No rush on this one; we can discuss when ready to show off v2.

**Comment by tomwayson** [comment]
This was resolved in [v1.1.1](https://github.com/Esri/angular-esri-map/releases/tag/v1.1.1)
