### ISSUE TITLE
Investigate bound "view-options" differences among esriMapView and esriSceneView

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#203]
The **esriMapView** and **esriSceneView** do not behave the same way with the binding of "view-options".  Supplying "view-options" to a `<esri-scene-view>` works as expected; however, attempting to do the same will NOT work with a `<esri-map-view>` (unless it is the `extent` property, which is the only one that works so far).

Refer to the Feature Layer and Scene View examples.

Investigate if this is an issue that can be isolated to JSAPI 4 beta3.  Otherwise, attempt to fix this repo's `setMap` method in **EsriMapViewController**.

**Comment by jwasil** [comment]
@tomwayson check it out: https://jsfiddle.net/jwasil/bb1uwbqz/
The bottom div MapView + Map recreates the issue with our current **esriMapView**, where if a `MapView` is created prior to having constructed and supplied a `Map`, then our requested properties (such as `rotation: 90`) are not accepted or paid attention to.  I think our directive can be adjusted to construct and handle things in a different order (as in the jsfiddle's top div example).

**Comment by jwasil** [comment]
Update: Yeah, I don't think the fix is all that intensive.  I just need to do it right such that the bound map to the **esriMapView** can be changed later at any time without needlessly re-constructing `MapView`s over and over.  If you take the jsfiddle above, and after everything is said and done, set the _top_ `MapView`'s map property to be the _second_ map, then things play nice for this situation.

**Comment by tomwayson** [comment]
by " after everything is said and done, set the top MapView's map property to be the second map" you mean something like: https://jsfiddle.net/tomwayson/zvd09L6b/

so would you plan be to only create the view once you have a map reference (i.e. via initial options, or when setMap is called?

**Comment by jwasil** [comment]
Exactly.

If we allow 2-way binding on **esriMapView** with a `map` property, then I assume we need to allow for constructing a `MapView` once, but allowing the `map` property to change any number of times.  How do you feel about that?

Currently, I am trying to work on constructing the `MapVew` once I have map reference (in the `setMap` method) if it doesn't already exist, otherwise simply set the `map` property.  I am open to other workflows and thoughts for sure on this.
