### ISSUE TITLE
Update custom directives test and patterns pages for v2?

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#204]
Honestly not too sure what would be a good example of something that would make sense as an example of a custom directive for v2, b/c w/ JSAPI 4, devs should be able to have a direct reference to the map object behind the map/scene view.

For v2beta.1 we may want to just hide the custom directive patterns pages (remove from TOC).

**Comment by jwasilgeo** [comment]
Just to clarify, a custom directive as in a custom mapping directive (how it was in the v1 paradigm--like `<parcel-map>`). Do I understand that right?  Wanted to make sure this is different than the new patterns page for widgets and directives in #233.

**Comment by tomwayson** [comment]
Yeah, I'm just having trouble thinking of a good example. I don't really think the blend renderer example for v1 showed the value of the pattern. Slight pref for 3d, but either is fine. Best I can find from v4 samples is the [query sample](https://developers.arcgis.com/javascript/beta/sample-code/tasks-query/index.html).

**Comment by jwasilgeo** [comment]
Oh, nice sample!  I feel like I totally missed that one before.  Pretty cool candidate for a custom view directive.

**Comment by tomwayson** [comment]
Closing as this repo is in maintenance mode.
