### ISSUE TITLE
Move live updating into separate test page

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#209]
Stemming from the (experimental) live updating established in #207 and @tomwayson's point to separate concerns, let's pull out the live updating bound properties and `$scope` from the lazy load / deferred test page and into a new test page.

@tomwayson, once this is more fleshed out, would we want to look into creating another patterns page outlining how developers can do the same themselves?  Or, would we want to create an example page that can do this kind of thing, as we had in some examples back in v1 (like using an `<input/>` to change the latitude)?

**Comment by tomwayson** [comment]
:+1:

What I really like about the way you coded this is that it exists *outside* the map/scene view directives so it's optional. That makes me feel like it could go either way (example page or patterns page), but I'm leaning towards example page - we can always change that later.

**Comment by jwasil** [comment]
:blush: thanks!

Test page for this issue in that case.  I can add a live binding example to our current working list over in #194.
