### ISSUE TITLE
New sample page for Bookmarks (v2beta2)

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#212]
Create a new sample page for [bookmarks](https://developers.arcgis.com/javascript/beta/sample-code/webscene-slides/index.html)

  This should ideally include:
- [x] test page
- [x] functional tests
- [x] example page in the gh-pages site
- [x] deal with info in comment below

Originates from #194.

**Comment by jwasil** [comment]
Functional tests have been written, but sometimes the webscene slides demo just doesn't load (both as a test page or within the gh-pages site).  Not sure if maybe setting the `self.map` property is within the angular digest cycle, which the `<esri-scene-view>` depends on to happen.

- [ ] More investigation is needed.

**Comment by jwasil** [comment]
See 12cb742835411d473fb8314e536ba6bbc4beff1d

**Comment by jwasil** [comment]
@tomwayson in continuing to use `$scope.$appy()`, I encountered a few times when scope was attempting to be applied when the digest cycle was already running, erroring the app or a sample page out.  Digging around some more online actually has led me to start trying to use [`$scope.$evalAsync`](https://code.angularjs.org/1.3.0/docs/api/ng/type/$rootScope.Scope#$evalAsync).

Some more here:
https://github.com/angular/angular.js/issues/2023, which led me to
https://groups.google.com/d/msg/angular/iXnA80JOZUg/PYD6KWjNbwkJ

See 6ff1fd422993af21d873378adab3915689605a5b

**Comment by tomwayson** [comment]
I've been thinking the `$scope.$apply()` issues we've been having are symptoms of larger problems, so I'm not real keen on `$scope.$evalAsync` as the solution. I've started on trying to diagnose the root causes and propose some fixes.

First, I noticed #219. Until we figure out what to do about that, it's probably safest to use the promise form of `esriLoader.require()` when experiencing async/digest weirdness.

Next, the call to `$sccope.$apply()` w/in the `view.then()` [here](https://github.com/Esri/angular-esri-map/blob/ae12d081a4ec640cddc747be5c8d413782047d5f/test/webscene-slides.html#L92-L103) makes sense, but it's inconsistent w/ the way the [v1 map directive's load event worked](https://github.com/Esri/angular-esri-map/blob/1e45fd121a90d0860aaaf3e24f944389fadc4378/src/map/EsriMapController.js#L176-L200). So I'm proposing the changes in #220.

@jwasil, please review #219 and #220 and let's have a pow-wow.
