### ISSUE TITLE
New sample page for chaining promises (v2beta2)

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#216]
Create a new sample page for [chaining promises](https://developers.arcgis.com/javascript/beta/sample-code/chaining-promises/index.html).  This should ideally include:
- [x] test page
- [x] functional tests
- [x] example page in the gh-pages site

Originates from #194.

**Comment by tomwayson** [comment]
Just a note to self(ves). I've seen occasionally where the promise example page (not test page) goes kinda nuts and then ends up here:

![image](https://cloud.githubusercontent.com/assets/662944/12683692/7b95563a-c66f-11e5-8b96-65f1b911c966.png)

Haven't isolated the circumstances yet.
