### ISSUE TITLE
esriLoader.require() callback form doesn't trigger digest cycle, but promise form does

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#219]
One thing I noticed when working with the webscene slides test page is that if I use the promise form of `esriLoader.request()` instead of the callback form, I can eliminate the need for `$scope.$apply()` / `$scope.$evalAsync()` [in at least one place](https://github.com/Esri/angular-esri-map/blob/ae12d081a4ec640cddc747be5c8d413782047d5f/test/webscene-slides.html#L84). Which makes sense, b/c the callback function gets called from w/in require's own callback, which is outside Angular's digest cycle. It works using the promise variant b/c the deferred's promise from $q will trigger the digest cycle.

A few options:
1) inject `$rootScope` and manually trigger the digest cycle with:
```
                    if (callback && typeof callback === 'function') {
                        callback.apply(this, args);
                        $rootScope.$digest();
                    }
```
^^^ that works, but haven't tested thoroughly. don't know how kosher that is though.

2) I think we can return a chained promise that calls the callback function, like:
```
return deferred.promise.then(function(args) {
  if (callback && typeof callback === 'function') {
    callback.apply(this, args);
  }
  return args;
})
```
haven't tested that^^^ yet

3) remove the callback form entirely <= less is more. :smile: 

Thoughts @jwasil?

**Comment by jwasil** [comment]
@tomwayson I appreciate you diving into the digest cycle woes.  I recall for v1 we had several discussions on how `esriLoader.require()` should look and behave, and what kind of conveniences it should have, but by now I find myself on board the less-is-more train.

If you think option 2 above is worth testing out (neat idea, BTW), then it could be a cool solution to providing a more Angular-friendly require callback.

I'm tempted to vote for option 3 right now after seeing it work for this version of the [webscene-slides test page](https://github.com/Esri/angular-esri-map/pull/220/files#diff-e37415e4b23a812b6a320a25704eb9ec).  I don't think the index position lookup for the loaded modules is all that disagreeable, but again that goes back to an older thread.

Any new thoughts or :bulb::exclamation: moments after having a chance to think on it more yourself?

**Comment by tomwayson** [comment]
I think it's worth trying to keep callback syntax, b/c is much more familiar to JSAPI users and I've noticed when converting sample pages it makes it much easier.

Option 1 is very easy to implement _naively_, but prob harder to do it _correctly_. Looking at the [$scope.$apply pseudo code](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$apply), it seems like we should wrap the callback in a try/catch and call `$exceptionHandler(e)` if it fails before finally calling `$digest()`.

Option 2 will require more changes to the code, but if it works, then we don't need to worry about all the 

We'd have to test either option and make sure we don't get those "already in digest" errs all over the place. To me, the best way to do that is to implement in both the 2.x and 1.x branches and run all the functional tests.

**Comment by jwasil** [comment]
@tomwayson I've made some preliminary progress with option 2 (for v2 examples like webscene-slides and search) and it looking really good!  Hopefully I'll have a chance to test it out in a few different situations and push something up soon.  Great idea and a wonderful code snippet above.
