### ISSUE TITLE
Bug in the legend : layers titles not included in the legend the second time it loads

### ISSUE THREAD

**Issue by jmrroy** [Esri/angular-esri-map#225]
Hi all,
I have got a new problem with the legend directive, for a while, but thought it comes from my code. The layer alias ( set by the title attribute) appears only the first time in the legend, when changing route and reload the map, the layer title are the original ones. You have the same problem on your example page. I don't know how to fix that..

**Comment by tomwayson** [comment]
Yep, I see it in our example page.

**Comment by jwasil** [comment]
Currently working on a fix for this @jmrroy.  We'll close this when the changes are ready.

**Comment by jmrroy** [comment]
Ok @jwasil , thank you very much!

**Comment by tomwayson** [comment]
@jmrroy

@jwasil fixed in the latest release - [v1.1.2](https://github.com/Esri/angular-esri-map/releases/tag/v1.1.2).

**Comment by jmrroy** [comment]
@jwasil and @tomwayson 
Thanks to you. It works great!
