### ISSUE TITLE
New patterns page for property binding

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#234]
Maybe just a link to the property binding example which includes the patterns.

**Comment by jwasil** [comment]
That'll work for sure. There's a lot of extra html in the snippets code block because of all the table-related html. Do you know of a way to trim that down to help users see what really matters (and that it really isn't that much code)?

**Comment by tomwayson** [comment]
Maybe the table related HTML moves to the patterns page and is replaced in the example page w/ a link to the patterns page. The patterns page would link back to the example for reference implementation.

**Comment by jwasil** [comment]
That sounds like a good plan to me.
