### ISSUE TITLE
Additional browser sniffing to prevent mobile devices from trying to load web scenes

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#243]
@jwasil discovered that the JSAPI docs use this regex to determine if a device has the WebGL capabilities needed to show a web scene:
```js
/Android|webOS|iPhone|iPad|iPod|BlackBerry|Opera Mini|IEMobile/i.test(navigator.userAgent)`
```

Even though our web scene examples pages now have error handlers, they don't fire for all devices (see #242). If the above test returns `true` we should show the warning about device not supporting WebGL and not try to load the web scene.

**Comment by jwasilgeo** [comment]
(It's @jwasilgeo now, :smirk: sorry for the annoyance.  Better to change my user name now before I'm _really_ famous...)
