### ISSUE TITLE
Ionic and angular-esri-map

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/angular-esri-map#263]
Research and look into the possibility of using this library within an [Ionic app](http://ionicframework.com/).

A place to get an idea of how another 3rd party can be integrated into Ionic:
[Firebase in Ionic](https://www.firebase.com/docs/web/libraries/ionic/guide.html) (see “Integrating Firebase” subsection, this one may be most direct as to what needs to be done as a developer)

**Comment by andygup** [comment]
I did get several questions about this concept at DevSummit. FWIW, this would also have to play well within the PhoneGap/Cordova life-cycle. Reference: https://github.com/Esri/quickstart-map-phonegap.

When it comes time, and if you need ideas feel free to ping me or @lheberlie

**Comment by jwasilgeo** [comment]
Thank you @andygup and @lheberlie! I have a feeling I'll definitely be looking for feedback and ideas.

**Comment by jwasilgeo** [comment]
For anyone following along...

I have been able to successfully incorporate **angular-esri-map** into an ionic project, which (**so far**) was as straightforward as following the patterns of this repo to instantiate an Esri JSAPI 4.x SceneView within the ionic/Angular JS code.

However, my current dev environment hasn't been great at emulating an Adroid device, so my next step is to see how this really behaves in a working emulation.  Then, we may have to dive deeper into the `deviceready` events that are shown in [Esri/quickstart-map-phonegap](https://github.com/Esri/quickstart-map-phonegap).  I want to better understand how that differs from ionic's [`ready`](http://ionicframework.com/docs/api/utility/ionic.Platform/#ready).

Once I have that going, I'll plan to create a demonstration repo.

**Comment by andygup** [comment]
Nice! I've had 2 questions about this in the last several weeks. 

Is there a public branch somewhere that you can share? I'd be happy to drop another set of eyes on it. If so, I have a fully functional Android dev environment + actual hardware to test on. cc @lheberlie

**Comment by jwasilgeo** [comment]
@andygup awesome, thanks.  Not yet, but I will create a new public repo and let you know.

**Comment by jwasilgeo** [comment]
Here we go! https://github.com/jwasilgeo/ionic-esri-map

**Comment by andygup** [comment]
@jwasilgeo I got the push permission email. I'll take an initial crack at it next week.

**Comment by jameshtlee** [comment]
Hi, regarding ionic + angular-esri-map, I followed the way it was documented here for the feature layer:
https://esri.github.io/angular-esri-map/#/examples/feature-layer

Vector tile works in ionic using the same method documented in the vector tile example, but when using feature layer, the map renders but the map is distorted.

Here is how the vector looks in ionic: http://i.imgur.com/LhOoaCp.png

Here is how the feature looks (Broken) : http://i.imgur.com/NngcUP7.png

**Comment by jwasilgeo** [comment]
@andygup perhaps we should make a mention of Ionic and your findings in the README--like we do for Angular2--to help devs who are traveling along their own Ionic quests in search of information?

**Comment by andygup** [comment]
Just an FYI for those perusing this issue, I've put together a simple Ionic 2 sample [here](https://github.com/andygup/ionic2-esri-map).
