### ISSUE TITLE
esri with angular JS

### ISSUE THREAD

**Issue by emazzu** [Esri/angular-esri-map#264]
hi, how are you, 

I would like, if using esri with angular JS, I can do the following ??

Which is your opinion ?

http://angular-ui.github.io/angular-google-maps/#!/demo

Esri is more complete ??

Regards
Eduardo

**Comment by jwasilgeo** [comment]
Hi @emazzu, thanks for your interest and for posting your question here.

There is a lot of functionality being used in that angular-google-maps demo site, and I would say yes, you can accomplish those things with Esri.  You can add layers to the map, draw and manipulate graphics, get access to the map instance, and more.

Anything that can be done with the [ArcGIS API for JavaScript](https://developers.arcgis.com/javascript/) you can also do within this **angular-esri-map** library. It is here to help you use Esri functionality with an Angular v1 application.  See [here](https://developers.arcgis.com/javascript/jssamples/) for Esri examples.

To integrate with Angular, I suggest looking at the [examples](https://arcgis.github.io/angular-esri-map-site-v1/#/examples) we have available to get specific ideas on how the code may look within Angular. The "Other Esri Modules" example demonstrates how to use one of the many modules in the ArcGIS API for JavaScript.

**angular-esri-map** also has more [documentation](https://arcgis.github.io/angular-esri-map-site-v1/#/patterns) on how to extend and customize to achieve the functionality you may need.

**Comment by bwcoleman18** [comment]
I would like to add information from a user standpoint.  Google Maps provides the familiar UI that many people are accustomed to outside of geographic information systems (GIS).  They also provide a means to provide more of an end user feel to things.  For instance, I have seen it used where a simple street map and street level view were used to spruce up GIS data for non-GIS folks.

IMHO, using the ESRI JS API though has much more benefits if you're a more GIS focused group.  I am not entirely sure about Google (been a while), but I don't believe they can easily read in data from a spatial server through an OGC format like WMS.  Also, I don't believe Google natively supports data coming from an ESRI Server's REST interface.  A quick look on the web showed some custom coded ways to do it, but implementing the ESRI JS API is a quicker and cheaper option.

Once you define your intended application then you can figure what tools best fit your needs.

**Comment by jwasilgeo** [comment]
@bwcoleman18 thanks for your added info and thoughts!
