### ISSUE TITLE
EsriMapController is not using explicit annotation and cannot be invoked in strict mode

### ISSUE THREAD

**Issue by GeorgeKnap** [Esri/angular-esri-map#269]
#### Please make EscriMapController compatible with angular's strict DI mode

Current latest bower package v 1.1.3 (angular-esri-map.js) contains EsriMapController which is not compatible with strict DI mode. 
Fun fact is that minified version is in strict DI  otherwise it would not work as far as I know.

Thanks

**Comment by jwasilgeo** [comment]
Hi @GeorgeKnap,

Your observation is correct that the minified dist files indeed adhere to strict DI.  Part of the build process takes care of that and applies it to the minified versions.  Can you tell us more about your particular situation or use case, and/or why having strict DI for the un-minified dist files would beneficial for you?

**Comment by GeorgeKnap** [comment]
Thank you for your comment. 
I am using gulp to create minified version of all third party libraries downloaded via Bower. wiredep plugin automatically scan all packages and build me script  dependency tree.  Then I simply use other gulp plugins to bundle all scripts into one file and minify them ( in case of production release). For development it's nice to have unminified versions of scripts. 
And of course my web app  is using angular strict di mode. 
I hope making this change won't be too much trouble for you. 

George

**Comment by jwasilgeo** [comment]
George, thanks for the additional info. This sounds like a good reason for us to make the change to the unminified dist files.

**Comment by jwasilgeo** [comment]
@GeorgeKnap the changes have been incorporated into the [`v1.x`](https://github.com/Esri/angular-esri-map/tree/v1.x) branch.  You can go ahead and use the latest code on that branch for now, since we may not be able to create a new tagged release until another week or so.

If you end up downloading that branch, you can do a fresh `npm install`, and then run `gulp build` to generate the uniminfied **dist** files. See [here](https://github.com/Esri/angular-esri-map/tree/v1.x#development-instructions) also.

**Comment by jwasilgeo** [comment]
The changes are also available on the `master` branch, for those who are using **v2** (JSAPI 4.x beta3+).

**Comment by jwasilgeo** [comment]
@GeorgeKnap happy Friday, @tomwayson was kind enough to quickly do a new tagged release.  You can go ahead and work with v1.1.4. https://github.com/Esri/angular-esri-map/releases/tag/v1.1.4

**Comment by GeorgeKnap** [comment]
Brilliant!  Thank you for the hard work!
