### ISSUE TITLE
esri-map-view directive not displaying the map

### ISSUE THREAD

**Issue by cabstool** [Esri/angular-esri-map#274]
#### Expected behavior

- I am implementing in a SPA and have all of the references to the 4.0beta3 stylesheet and 4.0beta3 script sources. I have a view and a controller and am using the esri-map-view directive. I have followed all of the example code that I can find.
- I expect that the directive will make the call, and do what is necessary to display the map in the <div> containing the directive. 

#### Actual behavior

- The directive makes the call and gets a response back with the name: World Street Map with all kinds of spatial and extent references; it looks good to me.
- The map is never displayed; the onCreate, onLoad, or onError are never called.
- There are no error messages at all; the response is 200 OK and has data.

#### Steps to reproduce the behavior
My code is as follows:

View:
```html
<div class="row" data-ng-controller="MapController as mapvm">
  <div class="col-md-6">
    <esri-map-view map="mapvm.map" 
      view-options="{scale: 50000000, center: [-101.17, 21.78]}"
      register-as="4rentmap"
      on-create="mapvm.onCreate"
      on-load="mapvm.onLoad"
      on-error="mapvm.onError">
    </esri-map-view>
  </div>               
</div>
```

Controller:
```
 (function () {
        'use strict';
        // see app.js 'esri.map'
        var controllerId = 'MapController'
       angular.module('app').controller(controllerId, ['common', 'esriLoader', MapController]);
         function MapController(common, esriLoader) {
        var getLogFn = common.logger.getLogFn;
        var log = getLogFn(controllerId);
        var logSuccess = getLogFn(controllerId, "success");
        var logError = getLogFn(controllerId, "error");

        var mapvm = this;
        mapvm.map = {};
        mapvm.onError = onError;
        mapvm.onLoad = onLoad;
        mapvm.onCreate = onCreate;

        // Creates the map
        esriLoader.require(['esri/Map'], function (Map) {
            mapvm.map = new Map({
                scale: 50000000,
                center:  [-101.17, 21.78],
                basemap: 'streets'
            });         
        });

        function onError(error) {
            logError("Map load Error");
        };

        function onLoad(evt) {
            log("Map loaded");
        };

        function onCreate(view) {
            log("Map created");
        };

    }
 
})();
```

Request that the directive sends:

Request URL:http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer?f=json
Request Method:GET
Status Code:200 OK (from cache)

Response:

{
 "currentVersion": 10.3,
 "serviceDescription": "This worldwide street map presents highway-level data for the world. Street-level data includes the United States; much of Canada; Mexico; Europe; Japan; Australia and New Zealand; India; South America and Central America; Africa; and most of the Middle East. This comprehensive street map includes highways, major roads, minor roads, one-way arrow indicators, railways, water features, administrative boundaries, cities, parks, and landmarks, overlaid on shaded relief imagery for added context. The map also includes building footprints for selected areas. Coverage is provided down to ~1:4k with ~1:1k and ~1:2k data available in select urban areas. The street map was developed by Esri using Esri basemap data, DeLorme basemap layers, U.S. Geological Survey (USGS) elevation data, Intact Forest Landscape (IFL) data for the world; HERE data for Europe, Australia and New Zealand, North America, South America and Central America, Africa, and most of the Middle East; OpenStreetMap contributors for select countries in Africa; MapmyIndia data in India; and select data from the GIS user community. For more information on this map, including the terms of use, visit us <a href=\"http://goto.arcgisonline.com/maps/World_Street_Map \" target=\"_new\" >online<\/a>.",
 "mapName": "Layers",
 "description": "This worldwide street map presents highway-level data for the world. Street-level data includes the United States; much of Canada; Mexico; Europe; Japan; Australia and New Zealand; India; South America and Central America; Africa; and most of the Middle East. This comprehensive street map includes highways, major roads, minor roads, one-way arrow indicators, railways, water features, administrative boundaries, cities, parks, and landmarks, overlaid on shaded relief imagery for added context. The map also includes building footprints for selected areas. Coverage is provided down to ~1:4k with ~1:1k and ~1:2k data available in select urban areas. The street map was developed by Esri using Esri basemap data, DeLorme basemap layers, U.S. Geological Survey (USGS) elevation data, Intact Forest Landscape (IFL) data for the world; HERE data for Europe, Australia and New Zealand, North America, South America and Central America, Africa, and most of the Middle East; OpenStreetMap contributors for select countries in Africa; MapmyIndia data in India; and select data from the GIS user community. For more information on this map, including the terms of use, visit us online at http://goto.arcgisonline.com/maps/World_Street_Map",
 "copyrightText": "Sources: Esri, HERE, DeLorme, USGS, Intermap, increment P Corp., NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), MapmyIndia, © OpenStreetMap contributors, and the GIS User Community",
 "supportsDynamicLayers": false,
 "layers": [
  {
   "id": 0,
   "name": "World Street Map",
   "parentLayerId": -1,
   "defaultVisibility": true,
   "subLayerIds": null,
   "minScale": 0,
   "maxScale": 0
  }
 ],
 "tables": [],
 "spatialReference": {
  "wkid": 102100,
  "latestWkid": 3857
 },
 "singleFusedMapCache": true,
 "tileInfo": {
  "rows": 256,
  "cols": 256,
  "dpi": 96,
  "format": "JPEG",
  "compressionQuality": 90,
  "origin": {
   "x": -2.0037508342787E7,
   "y": 2.0037508342787E7
  },
  "spatialReference": {
   "wkid": 102100,
   "latestWkid": 3857
  },
  "lods": [
   {
    "level": 0,
    "resolution": 156543.03392800014,
    "scale": 5.91657527591555E8
   },
   {
    "level": 1,
    "resolution": 78271.51696399994,
    "scale": 2.95828763795777E8
   },
   {
    "level": 2,
    "resolution": 39135.75848200009,
    "scale": 1.47914381897889E8
   },
   {
    "level": 3,
    "resolution": 19567.87924099992,
    "scale": 7.3957190948944E7
   },
   {
    "level": 4,
    "resolution": 9783.93962049996,
    "scale": 3.6978595474472E7
   },
   {
    "level": 5,
    "resolution": 4891.96981024998,
    "scale": 1.8489297737236E7
   },
   {
    "level": 6,
    "resolution": 2445.98490512499,
    "scale": 9244648.868618
   },
   {
    "level": 7,
    "resolution": 1222.992452562495,
    "scale": 4622324.434309
   },
   {
    "level": 8,
    "resolution": 611.4962262813797,
    "scale": 2311162.217155
   },
   {
    "level": 9,
    "resolution": 305.74811314055756,
    "scale": 1155581.108577
   },
   {
    "level": 10,
    "resolution": 152.87405657041106,
    "scale": 577790.554289
   },
   {
    "level": 11,
    "resolution": 76.43702828507324,
    "scale": 288895.277144
   },
   {
    "level": 12,
    "resolution": 38.21851414253662,
    "scale": 144447.638572
   },
   {
    "level": 13,
    "resolution": 19.10925707126831,
    "scale": 72223.819286
   },
   {
    "level": 14,
    "resolution": 9.554628535634155,
    "scale": 36111.909643
   },
   {
    "level": 15,
    "resolution": 4.77731426794937,
    "scale": 18055.954822
   },
   {
    "level": 16,
    "resolution": 2.388657133974685,
    "scale": 9027.977411
   },
   {
    "level": 17,
    "resolution": 1.1943285668550503,
    "scale": 4513.988705
   },
   {
    "level": 18,
    "resolution": 0.5971642835598172,
    "scale": 2256.994353
   },
   {
    "level": 19,
    "resolution": 0.29858214164761665,
    "scale": 1128.497176
   },
   {
    "level": 20,
    "resolution": 0.14929107082380833,
    "scale": 564.248588
   },
   {
    "level": 21,
    "resolution": 0.07464553541190416,
    "scale": 282.124294
   },
   {
    "level": 22,
    "resolution": 0.03732276770595208,
    "scale": 141.062147
   },
   {
    "level": 23,
    "resolution": 0.01866138385297604,
    "scale": 70.5310735
   }
  ]
 },
 "initialExtent": {
  "xmin": -3.366292934049552E7,
  "ymin": -2424171.6710013608,
  "xmax": 3.366292934049552E7,
  "ymax": 1.9172994125192165E7,
  "spatialReference": {
   "wkid": 102100,
   "latestWkid": 3857
  }
 },
 "fullExtent": {
  "xmin": -2.0037507067161843E7,
  "ymin": -1.9971868880408604E7,
  "xmax": 2.0037507067161843E7,
  "ymax": 1.99718688804085E7,
  "spatialReference": {
   "wkid": 102100,
   "latestWkid": 3857
  }
 },
 "minScale": 5.91657527591555E8,
 "maxScale": 70.5310735,
 "units": "esriMeters",
 "supportedImageFormatTypes": "PNG32,PNG24,PNG,JPG,DIB,TIFF,EMF,PS,PDF,GIF,SVG,SVGZ,BMP",
 "documentInfo": {
  "Title": "World Street Map",
  "Author": "Esri",
  "Comments": "",
  "Subject": "streets, highways, major roads, railways, water features, administrative boundaries, cities, parks, protected areas, landmarks ",
  "Category": "transportation(Transportation Networks) ",
  "AntialiasingMode": "None",
  "TextAntialiasingMode": "Force",
  "Keywords": "World,Global,Europe,Japan,Hong Kong,North America,United States,Canada,Mexico,Southern Africa,Asia,South America,Australia,New Zealand,India,Argentina,Brazil,Chile,Venezuela,Andorra,Austria,Belgium,Czech Republic,Denmark,France,Germany,Great Britain,Greece,Hungary,Ireland,Italy,Luxembourg,Netherlands,Norway,Poland,Portugal,San Marino,Slovakia,Spain,Sweden,Switzerland,Russia,Thailand,Turkey"
 },
 "capabilities": "Map,Tilemap",
 "supportedQueryFormats": "JSON, AMF",
 "exportTilesAllowed": false,
 "maxRecordCount": 1000,
 "maxImageHeight": 4096,
 "maxImageWidth": 4096,
 "supportedExtensions": "KmlServer"
}

Any help is appreciated. Thanks.

**Comment by cabstool** [comment]
ok, I put the esriloader.require inside of a function. Now I am getting a 404 on: http://js.arcgis.com/4.0beta3/esri/map.js

Any ideas?

**Comment by jwasilgeo** [comment]
@cabstool I appreciate you providing a good amount of information and code snippets.  This still would be easier and more straightforward for us to look into if you could recreate some of this in a live example, like on plnkr, jsfiddle, etc.  Would that be possible?  Thanks.

**Comment by cabstool** [comment]
No, my code is fairly wrapped up in an app with a REST back end. Using IE and looking at the console, I'm getting an object error on the dojoLoader on init.js:24 in //js.arcgis.com/4.0beta3/esri

**Comment by cabstool** [comment]
I'm having no problem at all using the ArcGIS Java API directly with version 3.16 of the API:

<style>
                 #map {
                    height: 50%;
                    width: 48%;
                    margin: 0;
                    padding: 0;
                }
            </style>
            <script>
                var map;
 
              require(["esri/map"], function(Map) {
                map = new Map("map", {
                  basemap: "streets",  //For full list of pre-defined basemaps, navigate to http://arcg.is/1JVo6Wd
                  center: [-97.0455903, 33.0665607], // longitude, latitude
                  zoom: 10,
                  scale: 50000000
                });
              });
            </script>
             <div id="map"></div>

**Comment by jwasilgeo** [comment]
Are you injecting this library into your overall module?  Example:
`angular.module('app', ['esri.map'])`

**Comment by cabstool** [comment]
Oh yes it wouldn't even get off the ground without that:

 var app = angular.module('app', [
        // Angular modules
        'ngAnimate',        // animations
        'ngRoute',          // routing
        'ngSanitize',       // sanitizes html bindings (ex: sidebar.js)
        'LocalStorageModule', // allows caching on browser local storage
        'ngFileUpload',
        'esri.map',

        // Custom modules
        'common',           // common functions, logger, spinner
        'common.bootstrap', // bootstrap dialog wrapper functions

        // 3rd Party Modules
        'breeze.angular',
        'breeze.directives',
        'ui.bootstrap'      // ui-bootstrap (ex: carousel, pagination,
dialog)
    ]);

**Comment by jwasilgeo** [comment]
@cabstool I cannot recreate the issue you originally describe.  I went ahead and in just a few minutes set up a new plnkr to investigate this, using your code snippets at the top, and did _not_ experience the following:
> The map is never displayed; the onCreate, onLoad, or onError are never called.

It seemed fine, but of course I did not have your common module, so I commented those references out.

I have a suspicion that something else might be interfering elsewhere in your application.  Without being in a position to help you debug with some kind of live example that includes more of the other moving parts, dependencies, and html, this will be a tough one for us to help out with since I don't see any obvious changes that need to be made.

**Comment by cabstool** [comment]
Thank you for your diligence and attempting to help out. I have the ArcGIS
JavaScript API working fine right now. I wish they had more help out there;
I'm trying to find some Zip code layers that I can add to the streets base
map, kind of frustrating...

On Thu, Apr 21, 2016 at 6:54 AM, Jacob Wasilkowski <notifications@github.com

**Comment by jwasilgeo** [comment]
Glad to try to help out.  I'll close the issue then if the original problem has been alleviated.  If you don't have your own zip code polygon layer to add to the map, you can search for all kinds of hosted layers and resources that you could use at arcgis.com.

**Comment by cabstool** [comment]
Yes hosted layers was what I was looking for but was having trouble
navigating their huge site. I'll look at again. Thank you.

On Thu, Apr 21, 2016 at 9:06 AM, Jacob Wasilkowski <notifications@github.com

**Comment by zish79** [comment]
@cabstool My map is also not shown with esri-scene-view directive. I have just simply follow the document they have in their official website.

http://esri.github.io/angular-esri-map/#/examples/scene-view

Can you please help me out here. What i am doing wrong.

**Comment by LyraelRayne** [comment]
For version 3 of the API you need to require "esri/map" not "esri/Map". The sample is written for esri4 which uses the upper case Map.

**Comment by tomwayson** [comment]
@zish79 

Are you able to get the [Quick Start example](https://github.com/Esri/angular-esri-map#quick-start) working?

If so, then the next step is to move over the HTML/JS code from the examples into your working page.

**Comment by gingerlyman** [comment]
@cabstool Here's what I've got so far... You get the 404 for the dependencies because the URL's for the get requests are not correct:

http://js.arcgis.com/4.0beta3/esri/map.js

Should be:

http://js.arcgis.com/4.0beta3/esri/Map.js

With the capital "M"ap.  But even if you list it that way in the dependency injection:

"esri/Map",

Somewhere along the line it gets changed to lowercase.
