### ISSUE TITLE
Declare dependencies in package.json and bower.json

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#275]
#### Expected behavior

- When installing from bower/npm, the dependencies (Angular 1.3+) should be installed (if not already)

#### Actual behavior

- Does not install Angular when installing from bower/npm

#### Steps to reproduce the behavior

Install from bower or npm in a new empty project, Angular 1.3 will not be installed.

I thought I had addressed this in #80, but apparently all I did was publish to npm. 

Need to also add the following to package.json and bower.json.

```
"dependencies": {
  "angular": "^1.3.0"
}
```

If we're interested in supporting browserify (no one has requested this so far) we'd also need to add an index.js [as described in this article](http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support). That could be it's own issue, b/c we'd also want to create a test page to verify that works.

**Comment by jwasilgeo** [comment]
Good catch.  And I'm down with supporting browserify, too.  Let's split it into another issue as you suggest?

**Comment by jwasilgeo** [comment]
**ALSO APPLY THESE CHANGES TO v1 BRANCH**
