### ISSUE TITLE
Support browserify

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/angular-esri-map#279]
#### Expected behavior
- Repo should support [Browserify](http://browserify.org/)
#### To do
- See initial comment at https://github.com/Esri/angular-esri-map/issues/275 for more context

> ...need to add an index.js [as described in this article](http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support). That could be it's own issue, b/c we'd also want to create a test page to verify that works.
- Add index.js
- Create a test page for verification
- Update README installation notes and CHANGELOG

**Comment by stanleyck** [comment]
Any news on this?

**Comment by tomwayson** [comment]
we are not actively working on this as no one has expressed an interest up until this point.

is this something you need? we'd gladly accept a pull request. It's always easier to implement this kind of thing if you have an actual use case. I can help if you're interested.

**Comment by tomwayson** [comment]
Closing as this repo is in maintenance mode.
