### ISSUE TITLE
Clarify documentation regarding Angular1 vs Angular2 support

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/angular-esri-map#285]
angular-esri-map v1 and v2 READMEs and docs site should
- continue to clarify that this repo is for Angular1
- provide some new docs on Esri & Angular2 resources (e.g. links to esri-system-js, webpack with Esri, demo/playground repos, dev summit presentation, ...)

**Comment by jwasilgeo** [comment]
@tomwayson I just started to add a section on Angular2 to the master README in 3af78b8, but I think it needs a helping hand.  Got any ideas on how to help convey what's out there?  I'd like to make sure there are enough links and info about the cool research into Webpack as well as esri-system-js.

I like how the slides explain this starting at http://jwasilgeo.github.io/esri-jsapi-and-angular-whats-next-dev-summit-2016/#/42, but that was before the glorious Webpack days.

As far as the docs site goes, here is a minimalist idea: maybe all we need is another blurb in the yellow alert, or some other 1-liner on the home page, that just points back to this section of the README?  Is there another straightforward way we could add info about Angular2 in the docs site?

cc @thollingshead if you have some other ideas too from your own experiments with Angular2

**Comment by tomwayson** [comment]
@jwasilgeo 

I think that blurb is very well written. One small suggested change:

In addition to the [Angular 2 specific information](http://jwasilgeo.github.io/esri-jsapi-and-angular-whats-next-dev-summit-2016/#/34) discussed in the [2016 "What's New, What's Next" presentation](http://jwasilgeo.github.io/esri-jsapi-and-angular-whats-next-dev-summit-2016) provided above, there are several resources available to inspire you to try out Esri+Angular2.

Beyond that, the only other things is that it might not be obvious to "normals" why you're breaking it down by System-js and Webpack, which makes perfect sense to us b/c we know that how you load the modules is the whole enchilada. I don't think I'd necessarily change anything based on that, just an observation I guess.

As far as the site goes, I would actually add a nav link for Angular 2 that points to this section of the README.

**Comment by jwasilgeo** [comment]
Thanks!  I'll let you know when I have a PR fired up.

**Comment by jwasilgeo** [comment]
Should finalizing the content of this wait until this is settled with esri-system-js? https://github.com/Esri/esri-system-js/pull/10

I may not have time for about another 1/2 week anyways to get back to this.

**Comment by tomwayson** [comment]
That PR has been merged. No need to wait for https://github.com/Esri/esri-system-js/issues/12 before you send people to esri-system-js.

**Comment by jwasilgeo** [comment]
Dev notes:

- [ ] apply same changes to v1 site/index.html and README
- [ ] deploy to gh-pages for both master and v1
