### ISSUE TITLE
esri-map-view not working in combination with routeProvider

### ISSUE THREAD

**Issue by jcobdice** [Esri/angular-esri-map#286]
#### Expected behavior

- Using esri.map in combination with $routeProvider would yield one ng-view with map present only for the view where the controller is called. 

#### Actual behavior

- <esri-map-view map="vm.map" view-options="{scale: 5000000, center: [-111, 46.5]}"></esri-map-view> When called in search.html yields no map. Map does load some pieces in inspector, but then nothing is displayed as if it is missing components. If map is applied at the index page level (is commented out in the sample for reproduction) the map displays just fine, but is on every page. This behavior is only possible with an in page controllerAs call and only on the body tag.

#### Steps to reproduce the behavior

**We can only help you if we're able to reproduce the behavior you describe above.** Please provide:

1. Please see PLUNKR link below. Create an index page containing a div for ng-view. Use routeProvider in angular.module to show two kinds of pages, one with map/one without. Visit page with map... it won't load. To get it to load uncomment page on PLUNKR's index page... map now loads but loads everywhere. 
2. Here is a [plunkr](https://plnkr.co/edit/EQ3Nm62lFFN9sC4H0f2d?p=preview)

**Comment by jwasilgeo** [comment]
@jcobdice I think you'll be happy to hear that the solution is straightforward.  JSAPI 4.0 seems to really want specific css height values for the `.esri-view` class.  Try out something like `height: 400px;` and you will be able to see the map view in your route.  I debugged this by inspecting the DOM and seeing that in fact the map view was being constructed as expected.

I will close this for now, but feel free to continue the discussion and re-open if there's anything else that comes up.

**Comment by jcobdice** [comment]
Well, I'll be... Thanks @jwasilgeo! You just saved me from a huge project work around.

**Comment by jwasilgeo** [comment]
I'm happy to hear that!
