### ISSUE TITLE
MapView don't display correctly

### ISSUE THREAD

**Issue by GeoAstronaute** [Esri/angular-esri-map#295]
Hi all,
I experience some problem by displaying a MapView with angular-esri-map2. I have actually absolutely no problem with SceneView.
Here is a code snippet that show the problem :[plnkr_example]( http://plnkr.co/edit/gjzJwgAcyJOfrchm2QDQ?p=preview)
I got the same result using  only a simple div element and esriLoader without any of your directive. 

Any Idea to fix that?

Thanks in advance for your help.

**Comment by jwasilgeo** [comment]
Please double check line 10 in your plnkr example index.html.  You need to make sure that the Esri CSS version is appropriate and matches the Esri JS version that is being used.

See code dependencies snippet: https://developers.arcgis.com/javascript/

https://github.com/Esri/angular-esri-map#dependencies

**Comment by GeoAstronaute** [comment]
Thanks @jwasilgeo, my mistake! Strange that the scene view correctly display with this css file.
