### ISSUE TITLE
missing closing </ul> bracket

### ISSUE THREAD

**Issue by kxgoto1927** [Esri/angular-esri-map#299]
#### Expected behavior

A small error in the documentation.  In the pop-up template, there should be a closing bracket for element <ul>.  Sorry, it's really minor I am sure the DOM still renders.

#### Actual behavior

List elements are contained within two opening <ul> brackets.

#### Steps to reproduce the behavior

http://esri.github.io/angular-esri-map/#/examples/popups

look within the 'content' property of the PopupTemplate object.

**Comment by jwasilgeo** [comment]
Hi @kxgoto1927, thank you for reporting this. :+1:  I checked that this is also the case for the [original sample](https://developers.arcgis.com/javascript/latest/sample-code/get-started-popupTemplate/index.html) that our example is based on.  I have reported it to the team responsible for the JSAPI samples, and we'll update our Angular sample here, too.

**Comment by jwasilgeo** [comment]
This has been changed appropriately in the new release of JSAPI 4.1, so I'll update the port of that sample here, too.
