### ISSUE TITLE
Cannot remove zoom buttons

### ISSUE THREAD

**Issue by skotturi** [Esri/angular-esri-map#300]
#### Expected behavior

- I'm trying to remove the zoom buttons

#### Actual behavior

- Cannot remove zoom buttons

#### Steps to reproduce the behavior

Here's my code:

```javascript
       esriLoader.require([
          'esri/Map',
          'esri/views/MapView',
          'esri/layers/FeatureLayer',
          'esri/widgets/Zoom'
        ], function (Map, MapView, FeatureLayer, Zoom) {
          // create the map
          self.map = new Map({
            basemap: 'hybrid',
          });

          // create a feature layer
          self.featureLayer = new FeatureLayer({
            url: '//services.arcgis.com/V6ZHFr6zdgNZuVG0/arcgis/rest/services/Landscape_Trees/FeatureServer/0'
          });

          // create MapView because according to: https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Zoom.html 
          // I should only bind widgets i.e. zoom instances, to MapView instances, not Maps. 
          var view = new MapView({
            map: self.map
          });

          // create Zoom widget instance.
          self.zoom = new Zoom({
              view: view,
              visible: false
          });
          
          console.log('Map is: ', self.map);
          console.log('MapView is: ', view);
          console.log('Zoom is: ', self.zoom)

          // add feature layer
          self.map.add(self.featureLayer);
});
```

- [Plunkr](https://plnkr.co/edit/EtDwvIdyMomf1iGMHQw1?p=preview) 

I've also tried setting `slider:false` when creating the map instance as [this post suggested](https://geonet.esri.com/thread/43876)
```javascript
 // create the map
          self.map = new Map({
            basemap: 'hybrid',
            slider: false
          });
```

I've looked through the [docs covering controls](http://esri.github.io/angular-esri-map/#/examples/home-button) but couldn't see anything. 

Thanks in advance,
Sante

**Comment by jwasilgeo** [comment]
@skotturi this can be changed with the JSAPI 4.x MapView or SceneView `ui` properties.

For example, you could do:
```javascript
view.ui.remove('zoom');
```

Or:
```javascript
var view = new MapView({
  map: self.map,
  ui: {
    components: ['attribution', 'compass']; // specify only the components you want
  }
});
```

**Comment by jwasilgeo** [comment]
https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#ui

**Comment by shahinfasihi** [comment]
var view = new MapView({
        container: "mapViewDiv",
        map: map,
        ui: {
            components: [] // i tried to hide zoomIn and zoomOut
        }
    });

**Comment by andygup** [comment]
@shahinfasihi Try this from sindie the `<esri-scene-view>` element:

`<esri-scene-view map="vm.map" view-options="{scale: 50000000, center: [-101.17, 21.78], ui:{components: []}}">`
