### ISSUE TITLE
TOC for v2 ??

### ISSUE THREAD

**Issue by snobrdinrtiste** [Esri/angular-esri-map#302]
Just wondering ... is there is an example of a TOC for v2 yet?

**Comment by jwasilgeo** [comment]
This repo does not have one yet but when JSAPI v4.x releases such a widget it should be straightforward to make it work in AngularJS using the patterns we recommend.  In the meantime, one could develop a custom TOC directive/component for their projects.  You could also connect with @Kollibri who worked on a custom TOC for JSAPI v3.x and angular-esri-map v1.  https://github.com/Kollibri/angular-esri-map-toc

**Comment by tomwayson** [comment]
The very soon to be released [v4.2 will include a layer list widget](https://blogs.esri.com/esri/arcgis/2016/12/09/whats-coming-in-the-arcgis-api-4-2-for-javascript/) that can be used directly w/ angular-esri-map.

**Comment by jwasilgeo** [comment]
@snobrdinrtiste did you see the release notes for the new JSAPI 4.2 release?  It includes a new layer list widget, as @tomwayson mentioned would be coming: https://developers.arcgis.com/javascript/latest/guide/release-notes/index.html#layerlist-widget
