### ISSUE TITLE
Add more required modules from ESRI

### ISSUE THREAD

**Issue by iMomen** [Esri/angular-esri-map#31]
Hello, 
I have a question .. 
How can i add more required modules from ESRI .. 
Something like : ( esri/symbols/SimpleMarkerSymbol ) ..
and How can i implement map function such as : ( disableScrollWheelZoom() ) ?

**Comment by tomwayson** [comment]
@iMomen 

See this fiddle to show how to get a reference to the map after it's loaded and set things like scroll wheel zooming (not that it is disabled by default so this example **enables** it):

http://jsfiddle.net/tomwayson/wh5jtxte/

As far as "add more required modules from ESRI .. " do you mean load them into your app, or create your own directives for them?

If you mean load them into your app, you can use the `esriLoader` service included in this module:

```js
esriLoader('esri/symbols/SimpleMarkerSymbol').then(function(SimpleMarkerSymbol) {
  // do something with SimpleMarkerSymbol
}); 
```
HTH

**Comment by tomwayson** [comment]
Assumed resolved. Closing for now.
