### ISSUE TITLE
Locator example for v2?

### ISSUE THREAD

**Issue by snobrdinrtiste** [Esri/angular-esri-map#326]
Is there an example that uses esri.tasks.Locator in v2?
I have tried to implement the Locator to geocode an address using the addressToLocations method and my locator keeps returning an error saying I need to specify a street value .. (which i already did)

var address = { Street: '300 N Grand Ave', ZIP: '90012' };
var locator = new Locator();
      locator.url = '//myserver:6080/arcgis/rest/services/Locator/Locator_13/GeocodeServer';
      locator.addressToLocations(address)
           .then(showAddressCandidates)
           .otherwise(rejectedPromise);

**Comment by tomwayson** [comment]
try `locator.addressToLocations({address: address })`

**Comment by snobrdinrtiste** [comment]
tried it every which way possible before i posted... i have even tried your suggestion with a static address and zone value but still getting that error
