### ISSUE TITLE
Bower package not working but NPM Is

### ISSUE THREAD

**Issue by Nick-t-go** [Esri/angular-esri-map#328]
Simple. I use the package installed using NPM and there is no problem. I use the package installed with bower and I get the following error. 
![error11](https://cloud.githubusercontent.com/assets/9603047/23285633/7ed280dc-fa00-11e6-8f65-f1fbdb7853c6.PNG)

**Comment by jwasilgeo** [comment]
The underlying error looks like code we already fixed in #314 when Angular 1.6.0 introduced some breaking changes.  Can you tell me more about what version of this library you have installed locally when you installed with bower?  And exactly what command did you run when using bower?

**Comment by Nick-t-go** [comment]
Originally I had these versions:
    "angular": "^1.5.8",
    "angular-animate": "^1.5.8",
    "angular-cookies": "^1.5.8",
    "angular-touch": "^1.5.8",
    "angular-ui-router": "^0.3.1",
    "angular-esri-map": "1.1.6"
I cloned the project on a new machine. Ran `bower install` bower then it installed new versions of packages:
    "angular": "1.6.2",
    "angular-animate": "1.6.2",
    "angular-cookies": "1.6.2",
    "angular-touch": "1.6.2",
    "angular-ui-router": "0.3.2",
    "angular-esri-map": "1.1.6"
Since your comment about conflicts with 1.6.0 I downgraded to the 1.5.8 versions and my project is working again. What do I have to do to get this to work with 1.6.X?

**Comment by jwasilgeo** [comment]
@Nick-t-go looks like you need to bump up to use version 1.1.8 of this repo to work with either Angular 1.5 _or_ 1.6.

If you're using JSAPI 4.x (which it doesn't appear to be the case), then you'd use version 2.02 of this repo.

The documentation (admittedly complex/confusing) on various Esri JSAPI, Angular, and angular-esri-map versions are noted here, but if you have any suggestions on how we can improve this please let me know.
https://github.com/Esri/angular-esri-map#dependencies
