### ISSUE TITLE
Vector Tile Layer not working

### ISSUE THREAD

**Issue by Nick-t-go** [Esri/angular-esri-map#335]
Using 4.3 API as in your samples. The Vector Tile Layers don't work. It doesn't work in the sample either. Is there a fix for this?

http://esri.github.io/angular-esri-map/#/examples/vector-tiles

`Uncaught TypeError: Cannot read property 'getParameter' of null`

**Comment by andygup** [comment]
@Nick-t-go Can you verify your browser and version? Maybe blow away your browser cache if you can.

Here's a jsbin of the vector tile sample code that works on Chrome 59 and Firefox 54 on both Mac and Windows: https://jsbin.com/soxodorogi/1/edit?html,output 

Does the jsbin link work on your machine?

**Comment by Nick-t-go** [comment]
It works now. I was on the phone with ESRI on Friday. First I was getting that error in my app. Second I went to your site. The example wasn't working and the console had the same error. Now. I wonder if there was an AGOL service issue as we were using the same Vector Tile Map for testing as you are. Not sure what is was but its working now. Thanks for the follow up I appreciate it.
