### ISSUE TITLE
Update README w/ status and up to date info on Angular 2(+)

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#339]
Somewhere near the top of the README we should:
- indicate that this repo is no longer being updated/tested w/ latest versions of the ArcGIS API and AngularJS
- Add a sentence like "You can find up to date information on [using the ArcGIS API in an Angular (2+) application at this Angular resources page](https://github.com/esri/jsapi-resources/tree/master/frameworks/angular).

We should then gut most, if not all of the the Angular "2" section below and replace it w/ the same sentence/link. Then we just keep that page up to date. The only things we might want to add over there are:
- links to https://github.com/beginor/systemjs-plugin-dojo and https://github.com/beginor/ng-esri-demo for the SystemJS crowd (if any of those people still exist)
- links to (maybe only the most recent?) DevSummit presentations

Thoughts?

**Comment by jwasilgeo** [comment]
Thanks for doing some maintenance and cleanup here, @tomwayson.  I agree with all of this.  I may also have some other ideas come to mind as I work on it.

What's the state of affairs these days with no-maintenance-intended badges in READMEs?  Is that still a thing?

**Comment by tomwayson** [comment]
@jwasilgeo that's pretty cool - I could use that on a project or two. 

That said, I'm not sure it's right for an Esri repo. I think we should be more explicit about exactly what our plans are w/ the repo. In this case, maybe add a **Status** section indicating that we:
- are not actively maintaining the repo (i.e. updating for and testing on latest versions of ArcGIS and Angular)
- not open to ideas for new features or pull requests
- will try to respond to bugs, but if they don't provide a link to an app/plunkr/bin/fiddle where we can verify, or we can't easily reproduce it ourselves in one of our existing apps, then it is unlikely that we'll be able to help (see #333)

Thanks for taking this on.

**Comment by jwasilgeo** [comment]
@andygup while we're in the process of noting in this repo's readme that we're not really maintaining it anymore and updating the now stale Angular 2+ info, are there any significant [Ionic readme changes](https://github.com/Esri/angular-esri-map#what-about-ionic) that should be made?

**Comment by andygup** [comment]
@jwasilgeo I'm with @tomwayson on gutting the Angular 2 section. I have one additional suggestion to Tom's bullet list that we add a blurb and a link to the `esri-loader` repo that it is now the preferred way to load ArcGIS JS API modules in Angular apps. WRT that change, I'll make a PR to update the `esri-loader` README to include a link to my Ionic repo.

**Comment by jwasilgeo** [comment]
Thanks @andygup and @tomwayson.  I'll tag you both as reviewers when I set up the PR for this.  Btw there will eventually be 2 separate PRs: 1 for `master` and another for `v1.x`.
