### ISSUE TITLE
Calcite bootstrap moved our cheese and broke gh-pages site

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#340]
#### Expected behavior

- the gh-pages site to not look like crap

#### Actual behavior

- the gh-pages site looks like crap

#### Steps to reproduce the behavior

Go to https://esri.github.io/angular-esri-map/ and observe:

![image](https://user-images.githubusercontent.com/662944/34568240-09ce63ca-f11a-11e7-8bd3-a5b609221640.png)

Looks like bad link to calcite-bootstrap, in the console: 
`Failed to load resource https://esri.github.io/calcite-bootstrap/assets/css/calcite-bootstrap-open.min.css: the server responded with a status of 404 ()`

**Comment by jwasilgeo** [comment]
Hopefully we can grab the `calcite-bootstrap-open.min.css` from this older release and it'll plug in just fine.

https://github.com/Esri/calcite-bootstrap/tree/v0.3.4/dist/css

(or back to v0.2.x if something isn't quite right)

**Comment by jwasilgeo** [comment]
Something else is off with their references to and deps on glyphicons throughout their v0.2 and v0.3 releases.  At this rate I'll get the docs sites back to looking acceptable and will probably just ignore or remove broken `span`s that were for glyphicons.
