### ISSUE TITLE
AngularJS goes into Long Term Support on July 1, 2018

### ISSUE THREAD

**Issue by andygup** [Esri/angular-esri-map#345]
AngularJS is planning one more significant release, version 1.7, and on July 1, 2018 it will enter a 3 year Long Term Support (LTS) period. After the release of 1.7.0 the team does not intend to merge any feature or fix that will require even a minor breaking change.

Additional information: https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c

Please plan accordingly. If you are starting a new project we recommend you use [`esri-loader`](https://github.com/Esri/esri-loader) with [Angular](https://angular.io/) (v2+). 

/cc @tomwayson @jwasilgeo

**Comment by andygup** [comment]
FYI for those still on AngularJS, Angular 6 was recently launched and is yet another reason to consider migrating off AngularJS (v1).

https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4
https://github.com/angular/angular/releases

**Comment by tomwayson** [comment]
Or if Angular and TS aren't your thing, you might like [Vue.js](https://vuejs.org/), which [also works well w/ esri-loader](https://github.com/Esri/esri-loader#vuejs).

Either way, we should consider this library in LTS as well.
