### ISSUE TITLE
Map loads only certain tiles 

### ISSUE THREAD

**Issue by androidparth90** [Esri/angular-esri-map#347]
#### Expected behavior
Map should load all tiles

#### Actual behavior
Map is loading only some of the tiles

#### Steps to reproduce the behavior
Include a simple base map and load the same using esri-loader in Angular 4 project

Versions : 
Node : v6.11.4
Angular cli - v1.4.9
Esri : v3.23

Code snippet

HTML : 

<div id="mapNode"></div>

CSS : 
@import 'https://js.arcgis.com/3.23/esri/css/main.css';

html,
body,
#mapNode {
  padding: 0;
  margin: 0;
  height: 100%;
  width: 100%;
}

Typescript: 
`	import {Component, OnInit, ViewChild, ElementRef, Input, Output, EventEmitter} from '@angular/core';
	import { loadModules } from 'esri-loader';
	import esri = __esri;

	@Component({
	  selector: 'app-esri-map',
	  templateUrl: './esri-map.component.html',
	  styleUrls: ['./esri-map.component.css']
	})

	export class EsriMapComponent implements OnInit {

	  // Private vars with default values
	  private _zoom = 10;
	  private _center = [95.7129, 37.7041]; //long,lat pair
	  private _basemap = 'streets';

	  @Input()
	  set zoom(zoom: number) {
		this._zoom = zoom;
	  }

	  get zoom(): number {
		return this._zoom;
	  }

	  @Input()
	  set center(center: any[]) {
		this._center = center;
	  }

	  get center(): any[] {
		return this._center;
	  }

	  @Input()
	  set basemap(basemap: string) {
		this._basemap = basemap;
	  }

		 get basemap(): string {
		   return this._basemap;
		  }

	   @Output() mapLoaded = new EventEmitter<boolean>();

		// this is needed to be able to create the MapView at the DOM element in this component
		@ViewChild('mapViewNode') private mapViewEl: ElementRef;

	  constructor() { }

	   public ngOnInit() {
			  const options = {
					url: 'https://js.arcgis.com/3.23/' 
				} ;
				 loadModules(["esri/urlUtils", "esri/map", "esri/dijit/Directions",
				 "dojo/parser", "esri/layers/ArcGISDynamicMapServiceLayer",
			  "esri/layers/GraphicsLayer","esri/renderers/SimpleRenderer", 
			   "esri/symbols/SimpleMarkerSymbol","esri/symbols/SimpleLineSymbol","esri/SpatialReference",
				  "esri/Color","esri/graphic", 
				"esri/geometry/Point","esri/tasks/FeatureSet","esri/symbols/PictureFillSymbol",
				"dijit/layout/BorderContainer", "dijit/layout/ContentPane", "dojo/domReady!"
		  ], options)
		  .then(([ urlUtils, Map, Directions,
				 parser,ArcGISDynamicMapServiceLayer,GraphicsLayer,
			  SimpleRenderer,SimpleMarkerSymbol,SimpleLineSymbol,SpatialReference,
			   Color,Graphic,Point,FeatureSet,PictureFillSymbol
		  ]) => {
			 parser.parse();
		 
		  // create map with the given options at a DOM node w/ id 'mapNode'
		  let map = new Map('mapNode', {
			center: [95.7129, 37.7041], //long,lat pair
			zoom: 4,
			basemap: 'streets' //possible values ==> streets, topo, hybrid
		  });
		  
		})
		.catch(err => {
		  // handle any script or module loading errors
		  console.error(err);
		});

	   } // ngOnInit
	}`

Attached screenshot for reference.

`

**Comment by androidparth90** [comment]
![screenshot](https://user-images.githubusercontent.com/6248876/36389627-bda260a2-15c5-11e8-937e-4aa75898be3d.png)

**Comment by jwasilgeo** [comment]
@androidparth90 have you inspected your network traffic for any invalid resources?  The CSS from Esri you're trying to load does not exist at that path and should be showing a 404 error in your network traffic.

See:
- https://developers.arcgis.com/javascript/3/ (the css url  is listed there on the homepage)
- https://developers.arcgis.com/javascript/3/jshelp/css.html (more info)



`@import 'https://js.arcgis.com/3.23/esri/css/main.css';`
-->
`@import 'https://js.arcgis.com/3.23/esri/css/esri.css';`

**Comment by androidparth90** [comment]
hi @jwasilgeo ok let me try with the CSS URL you have mentioned and get back to you

**Comment by androidparth90** [comment]
Hi @jwasilgeo After using the CSS link --> https://js.arcgis.com/3.23/esri/css/esri.css. My issue was resolved. Thank u very much. You may close this issue please
