### ISSUE TITLE
GraphisLayer extent ??

### ISSUE THREAD

**Issue by snobrdinrtiste** [Esri/angular-esri-map#348]
i'm trying to use the MapView's .goTo() function to zoom into a GraphicsLayer which containts both a point and a polygon graphic ...
ex:  mapview.goTo(graphiclayer.graphics)

i've tried skipping the graphicslayer and directly adding the graphics to the mapview ...
ex: 
mapview.graphics.addMany([pointgfx, polygfx]);
mapview.goTo(vm.mapview.graphics);

nothing seems to work...
can someone point me in the right direction?

**Comment by andygup** [comment]
That's strange, maybe try a quick test using a single `Graphic.geometry`? Or, maybe create a separate Graphic's Collection and try injecting that into `mapview.goTo()`?

**Comment by snobrdinrtiste** [comment]
tried just adding a single graphic to the mapview and not using a graphiclayer ...
                                

                                var polygonsymbol = {
                                    type: "simple-fill", 
                                    color: [68, 68, 68, 0.25],
                                    style: "solid",
                                    outline: { 
                                        color: "#cc0000",
                                        width: 3
                                    }
                                };
                                var ncgraphic = new Graphic({
                                    geometry: Poly,
                                    symbol: polygonsymbol
                                });
                                vm.mapView.graphics.add(ncgraphic);
                                vm.mapView.goTo(ncgraphic.geometry);

the graphic gets added to the mapview but its extent does not get zoomed into the graphic's geometry

**Comment by jwasilgeo** [comment]
1. How does AngularJS, Angular, or angular-esri-map play a role in this issue?

2. Can you recreate your described behavior in standalone sample?

I was able to get it to work by adding this line to this sample:

https://developers.arcgis.com/javascript/latest/sample-code/intro-graphics/index.html

`setTimeout(function() { view.goTo(view.graphics); }, 2000);`

**Comment by snobrdinrtiste** [comment]
wow... so it seems like the mapview needs a couple seconds to register the graphics ...
thank you very much ... setting a timeout worked for me too

**Comment by jwasilgeo** [comment]
@snobrdinrtiste I would advise against relying on `setTimeout`.  That was just for a quick test.

You should rely on [`view.when...`](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html) as you continue to work with JSAPI v4.

**Comment by snobrdinrtiste** [comment]
@jwasilgeo thanks for the heads up... i was actually reading up on that Promise while in my meeting just now...  i'll definitely try that out.  thanks for all your help!!!!

**Comment by andygup** [comment]
Here's a good overview of working with promises in the JS API v4 https://developers.arcgis.com/javascript/latest/guide/working-with-promises/index.html
