### ISSUE TITLE
Short video tutorial

### ISSUE THREAD

**Issue by hhkaos** [Esri/angular-esri-map#349]
Hi guys!

I have just created a short video tutorial you might want to add to the README:

[![how to - angular 5 and arcgis api for js 4 x](https://user-images.githubusercontent.com/826965/39322104-1230e5d4-4989-11e8-84b8-09b945ca7d30.gif)
](https://www.youtube.com/watch?v=ZEH9kOwDgx0)

Cheers!

**Comment by andygup** [comment]
Sweet! I'll open an issue over on: https://github.com/Esri/angular-cli-esri-map. 😀

**Comment by hhkaos** [comment]
Thanks Andy! :smile:

**Comment by tomwayson** [comment]
Closing in favor of https://github.com/Esri/angular-cli-esri-map/issues/10
