### ISSUE TITLE
Testing the ArcGIS online sample shows error view.then is undefined

### ISSUE THREAD

**Issue by malibeg** [Esri/angular-esri-map#350]
Got error in Chrome when testing [Arcgis sample for angular.js](https://developers.arcgis.com/javascript/latest/sample-code/widgets-frameworks-angular/index.html)

I get same error when trying to integrate directive into my angular.js code. 

angular.js:14800 TypeError: self.view.then is not a function
    at angular-esri-map.js:421
    at processQueue (angular.js:17169)
    at angular.js:17217
    at Scope.$digest (angular.js:18352)
    at angular.js:18581
    at completeOutstandingRequest (angular.js:6428)
    at angular.js:6707 "Possibly unhandled rejection: {}"
(anonymous) @ angular.js:14800

**Comment by malibeg** [comment]
When testing with arcgis api 4.6 it works ok. It gives this warning [esri.core.Promise] DEPRECATED: then() -- use .when(callback, errback) instead

**Comment by andygup** [comment]
@malibeg please note, this project is not actively being maintained: https://github.com/Esri/angular-esri-map#status and [AngularJS has entered long term support](https://github.com/angular/angular.js?files=1#angularjs-will-be-moving-to-long-term-support-lts-mode-on-july-1st-2018-find-out-more). All of our current dev efforts are on Angular 5+ https://github.com/Esri/angular-cli-esri-map. 

Pull requests are welcome if you have time to create one!

**Comment by andygup** [comment]
Oh, my bad. Thanks for the heads-up. We are addressing the broken sample over on developers.arcgis.com

**Comment by tomwayson** [comment]
resolved in #351
