### ISSUE TITLE
Is there a wrapper for Angular2+

### ISSUE THREAD

**Issue by sreekumarp** [Esri/angular-esri-map#353]
Is there a wrapper for Angular2+

**Comment by andygup** [comment]
For others with the same question, for Angular 2+ we recommend using `esri-loader`. Here's a sample repo demonstrating Angular CLI + `esri-loader`: https://github.com/Esri/angular-cli-esri-map. And, FYI, we currently don't support any webpack patterns for Angular 6+ until their webpack eject story gets settled and officially documented.
