### ISSUE TITLE
How to use our own basemap?

### ISSUE THREAD

**Issue by Kollibri** [Esri/angular-esri-map#43]
How would I modify this to use our own basemap?  I have tried the following, but it results in an error:

"Uncaught TypeError: Cannot read property 'query' of null"

I have modified the esriMap directive as follows just to try forcing it to the new basemap:

Inside the controller, I have the following code:

<pre>
require(['esri/map', 'esri/arcgis/utils', 'esri/basemaps'], function (Map, arcgisUtils, esriBasemaps) {
                    esriBasemaps.mcgiStreet = {
                        baseMapLayers: ['http://ourserverhere/arcgis/rest/services/BaseMap/StreetMap_tpt/MapServer'],
                        thumbnailUrl: 'http://servername.fqdn.suffix/images/thumbnail_2014-11-25_61051.png',
                        title: "Streetmap Transparent"
                    };
</pre>

And then further down where the basemap is set, I have the following:
<pre>
mapOptions.basemap = "mcgiStreet";
</pre>

This is based off the example using the basemaps select box, and info from the following URL:
https://developers.arcgis.com/javascript/jsapi/esri.basemaps-amd.html

I'm relatively new to angular so I could be doing something wrong that is quite simple.  Thank you for any help you can provide.

**Comment by tomwayson** [comment]
I've never loaded a custom basemap in that way, but it looks valid based on the example in the JSAPI docs.

Are you working off of one of the test pages, or off of pages in the docs? Right now there's a bug in the docs, see #38.  If you're working there, try in one of the [test pages](https://github.com/Esri/angular-esri-map/tree/master/test) - they are served by gulp at the site root level, so http://localhost:9002/simple-map.html

LMK if that was the issue. If not, you might try using the exact "delorme" URLs from the example in the docs.

**Comment by Kollibri** [comment]
Ah...  I made a typo.....

The "baseMapLayers" option is an object with a property called "url".  I didn't have that in right.

Sorry to have wasted your time.

Thank you for responding!

**Comment by tomwayson** [comment]
np - good to know this works!
