### ISSUE TITLE
Identify example?

### ISSUE THREAD

**Issue by Kollibri** [Esri/angular-esri-map#44]
Is there an example of using an identifyTask similar to how the FeatureLayer directive is done?

I was hoping to make an angular directive that would look something like this in the html:
`<esri-map>
      <esri-identify-task url="myurl" layerIDs="[0,3]" infoWindowTemplate="html template here"></esri-identify-task>
</esri-map>`

I am trying to modify the "FeatureLayer" directive to handle an identify task instead, but since an identify task doesn't "fire" when the map is loaded, the architecture seems a bit different.  Is there an example that would show how to wire up the identify task to the map click event using the angular style?

**Comment by tomwayson** [comment]
If you want to create a generic, reusable directive, the legend directive might be a better example in this case. You should be able to get a reference to the map in your directive by calling [mapController.getMap()](https://github.com/Esri/angular-esri-map/blob/master/src/directives/esrilegend.js#L29). Then you have a reference to the map which you can use to bind the identify task to a click event handler. You should probably include something like [this block](https://github.com/Esri/angular-esri-map/blob/master/src/directives/esriMap.js#L239) at the end of your directive's controller to remove your handler. 

If you go that route, we'll welcome a PR here, however, if you're not really trying to create something that is reusable and generic, and instead are trying to handle more application specific logic, I'd suggest some other options:

1. You could just handle the map's load event in your application's controller (see the [map events example](http://esri.github.io/angular-esri-map/#/examples/map-events)) and then use the [esriLoader](https://github.com/Esri/angular-esri-map/blob/master/src/services/esriLoader.js) to load the identify task and then bind it to the map's click event right in your controller (or in a service) at the application level - this should be much simpler.
2. If you have a lot of custom interaction w/ the map, you may want to roll your own directive following [my parcel map sample](https://github.com/tomwayson/angular-parcel-map).

**Comment by Kollibri** [comment]
I got it working.  I'm not real familiar with git though.  I will work on trying to get a sample uploaded properly so you can see how I implemented it.

**Comment by Kollibri** [comment]
#52  PR is made.

**Comment by tomwayson** [comment]
#52 adds the ability to set an info window for a dynamic service layer, which handles binding the map click to performing identify and displaying the pop up for the configured layers.
