### ISSUE TITLE
Call legend AFTER layers are done loading

### ISSUE THREAD

**Issue by Kollibri** [Esri/angular-esri-map#47]
How should we modify this code to force the legend directive to not run until after all the layers have been added to the map?  I'm getting an issue where the "layerInfos" property is not filled at the time the legend directive fires because the map layers are not yet added to the map.  I'm not sure how to delay the legend directive until the layers are done loading.

**Comment by Kollibri** [comment]
I got this working by making the following changes:

In esriLegend.js I modified the watch method to be as follows:

<pre>
scope.$watchCollection(function () { return mapController.getLayerInfos(); }, function (newValue, oldValue, scope) {
                              legend.refresh(newValue);
                          });
</pre>

In esriMap.js I modified the "addLayerInfo" and "getLayerInfos" calls to use a scope variable instead of "this".

<pre>
this.addLayerInfo = function (lyrInfo) {
                    return self.getMap().then(function (map) {
                        if (!$scope.layerInfos) {
                            $scope.layerInfos = [lyrInfo];
                        } else {
                            $scope.layerInfos.push(lyrInfo);
                        }
                        return $scope.layerInfos;
                    });
                };

                this.getLayerInfos = function () {
                    return $scope.layerInfos;
                };
</pre>

Now it is watching the layerInfos object for changes and updating the legend appropriately.  I'm not sure if this is the "right" way to do it or not.  But it works.

**Comment by tomwayson** [comment]
@Kollibri 

Would you be willing to make a pull request of your changes so that it is easier for me to review the code.

**Comment by Kollibri** [comment]
Yes I am willing I'm just not very experienced with git so will have to spend a little time on that first.  Will try to get this up to you within a few days.

**Comment by Kollibri** [comment]
#52 PR is made.

**Comment by tomwayson** [comment]
Added in #52

Thank you @Kollibri.
