### ISSUE TITLE
AngularJS ESRI TOC?

### ISSUE THREAD

**Issue by Kollibri** [Esri/angular-esri-map#50]
I am wondering if there is an angular js ESRI TOC similar to this one:

http://gmaps-utility-gis.googlecode.com/svn/tags/agsjs/latest/docs/toc/examples.html

I am looking to create a TOC that is similar but was hoping for some guidance on where to start,  Originally i thought perhaps I could make a directive that would be a child of the legend directive, but there are features in the example TOC that I'd like to have that I'm not sure will easily translate if I do it that way (like graying out layers that are out of scale).

Do you have any suggestions on on to proceed or any examples that would be best to start from?  Thanks again for your help! =)

**Comment by tomwayson** [comment]
I'm not aware of anyone that has done this.

I would start by copying the legend directive and making a directive that is a child of the map and a peer (not a child) of the legend directive.

You'll also need to add the css and `dojoConfig` to index.html as [they describe](http://gmaps-utility-gis.googlecode.com/svn/tags/agsjs/latest/docs/toc/examples.html).

**Comment by tomwayson** [comment]
Also, I'm closing this as it is not likely something that will make it's way into this repo and if you want to continue this discussion, it's probably best to [do it in a forum](https://github.com/Esri/angular-esri-map/blob/master/CONTRIBUTING.md).
