### ISSUE TITLE
Adding Points of locations to the Esri map

### ISSUE THREAD

**Issue by Quinten-Savenberg** [Esri/angular-esri-map#53]
I'm trying to make a application so I can put my Spatial data on in my application with Points.

Now i have the problem that when i try to add these points by adding them to the map through graphics I get the error that it doesn't know the graphics function however i added esri/graphic to the require..

Any idea how I can fix this, I'm kinda new to the whole AngularJS.

Thanks

**Comment by tomwayson** [comment]
@Quinten-Savenberg your best chance for getting an answer to this kind of question is to post to a forum with a relevant code snippet , see: 

https://github.com/Esri/angular-esri-map/blob/master/CONTRIBUTING.md#before-filing-an-issue

If you post a question in one of those places I will try to answer.

**Comment by tomwayson** [comment]
Closing as I never saw any follow up. If you posted a question to the forums and I missed it, please post link and I'll take a look.
