### ISSUE TITLE
Not support AngularJS v1.3.0

### ISSUE THREAD

**Issue by rbonillajr** [Esri/angular-esri-map#57]
Hi, i use angular 1.3 but angular-esri-map not work. Can you upgrade to this version?.

**Comment by eas604** [comment]
Hi @rbonillajr ,

`angular-esri-map` works for me with Angular 1.3.14. What problems are you experiencing?

**Comment by rbonillajr** [comment]
yep works but send this errors. "Multiple Define"

![image](https://cloud.githubusercontent.com/assets/8268226/7712534/762a4814-fe37-11e4-9c3b-3398b5da9530.png)

**Comment by eas604** [comment]
Looks like this is something you can bring up on [GeoNet](https://geonet.esri.com/tags/#/?tags=angular-esri-map) or [GIS StackExchange](http://gis.stackexchange.com/questions/ask?tags=angular-esri-map,arcgis-javascript-api,angularjs).
