### ISSUE TITLE
Supporting Lazy Loading of Dojo/ESRI Javascript API 

### ISSUE THREAD

**Issue by ScottONeal** [Esri/angular-esri-map#58]
Is there any interest in creating the functionality to defer loading of Dojo/Digit and all of the ESRI modules? I have a use case within a SPA to only load ArcGIS maps only if certain conditions are met. By defering loading, it would remove the need to require all angular-esri-map (Dojo, Dijit resources until needed).

angular-google-maps moved to this paradigm. If there is interest I can start PR for it.

**Comment by tomwayson** [comment]
closed by #60
