### ISSUE TITLE
How to load maps from a mapserver?

### ISSUE THREAD

**Issue by dkwin** [Esri/angular-esri-map#61]
Sorry if this is obvious but I'm relatively new to ESRI, I was wondering how I could load a map from a map server as opposed to a feature from a feature server.  

Basically, if I could add a ArcGISDynamicMapServiceLayer through the controller or the directive, it'd be great.

Is this possible?

**Comment by eas604** [comment]
Hi @dkwin ,

Pull request #52 includes a directive for `DynamicMapServiceLayer`, but this PR hasn't been merged yet.

If you need this directive immediately, you can use @Kollibri's branch manually I suppose.

**Comment by jwasil** [comment]
@dkwin you could also create your own Angular Esri map directive, and bring in your map layers as normal through the Esri JavaScript API.  Check out these repos for examples:

* solid example of how you can wrap up an Esri JavaScript map into an Angular directive: [tomwayson/angular-parcel-map](https://github.com/tomwayson/angular-parcel-map)
* [my own demo playground repo](https://github.com/jwasil/angular-esri-playground#inspiration--guidance), and a [directive](https://github.com/jwasil/angular-esri-playground/blob/master/app/esriPointRenderersMap.js) that adds Esri `FeatureLayer`s to the map

**Comment by jwasil** [comment]
PS: @dkwin, please check out this comment https://github.com/Esri/angular-esri-map/issues/42#issuecomment-91251901, and also https://github.com/Esri/angular-esri-map/blob/master/CONTRIBUTING.md.  Thanks!

**Comment by jwasil** [comment]
@dkwin something else crossed my mind. If you don't want to make your own map directive and bring your map layers in via the `ArcGISDynamicMapServiceLayer` using AMD, you could add each layer individually from your MapService through `FeatureLayer`s.

http://esri.github.io/angular-esri-map/#/examples/feature-layers

**Comment by dkwin** [comment]
Thanks Jwasil and Eas604, I just got back on this and I'll try to contribute what I can.

**Comment by tomwayson** [comment]
@dkwin we've added a dynamic map service layer in 9f79bdb69d0f2c0aed23ccdd68240828dce95587 and it will be part of the Beta 5 release.
