### ISSUE TITLE
update to JSAPI 3.14

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#66]

**Comment by jwasil** [comment]
@tomwayson 3.14 is in: https://github.com/Esri/angular-esri-map/commit/3fb0c220cf02075c320850005634db3c52d8fb55

Didn't document via GitHub issues, and hope I didn't miss anything along the way.

**Comment by tomwayson** [comment]
Great!

Then I just need to update the [recently updated esriLoader](https://github.com/Esri/angular-esri-map/blob/1502db5738681e384e8e6b582ce6dc9dcc3f83b4/src/services/esriLoader.js#L35).
