### ISSUE TITLE
Move core services (esriLoader) to own module ('esri.core')?

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#69]
I want to enable the "roll your own custom map directive" pattern (as demonstrated in  https://github.com/tomwayson/angular-parcel-map), as this will make it easier to spin up gists/fiddles/repos that demonstrate how to use newer angular 1.x patterns (`controllerAs`, `bindToController`, using a module loader like browserify, and ES6) that help prepare for 2.0.

At the same the community is continuing to build out the declarative mapping directives here. I want to encourage that w/o causing those that just need the esriLoader for their own custom directive to have to deal w/ the increasing complexity and versions that come w/ all those community contributions.

I'm thinking the "core" is pretty much just the esriLoader at this point. That could be made into it's own angular module ("esri.core") and the "esri.map" module could declare that as a dependency.

Thoughts? Feelings?

**Comment by jwasil** [comment]
@tomwayson I think that's a great idea.  I find that when I "roll" my own map directives, I end up pulling in all of `esri.map` module when I really just want the functionality of **esriLoader** as well as **esriRegistry**.  For example, see [here at lines 17 & 19](https://github.com/jwasil/angular-esri-playground/blob/master/app/esriGeocode-mdAutocomplete.js#L17) (note: this example is pre-PR #60).

Any other thoughts form you or the community?  I say let's do this!

**Comment by tomwayson** [comment]
resolved by #135
