### ISSUE TITLE
Edit the subtitle/description of the "Simple map" on the gh-pages Examples page

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#70]
This line looks like it might be missing part of its description: https://github.com/Esri/angular-esri-map/blob/master/docs/app/examples/examples.html#L9

**Comment by jwasil** [comment]
@tomwayson I could knock this out while doing PR #71.  I couldn't find the right wording when I looked briefly at the history the other day, but I'm already working with the examples.html and I could add something like:
```html
<p>Simplest possible map - simply setting the center, zoom, and basemap.</p>
```

Or, I can just leave it be for now and we can handle it in another PR to keep a separation of concerns.  Your thoughts on doing it under my current PR, and if so, on the wording?

**Comment by tomwayson** [comment]
Now that center/zoom/basemap are all optional attributes and we can instantiate a map w/ options, I'm not sure it's accurate to call this the "simplest possible map."

How about:
```html
<p>A simple example of two way data binding to a map's center and zoom level.</p>
```

**Comment by jwasil** [comment]
:+1: I like it!

**Comment by jwasil** [comment]
Oh but wait a second...really similar wording to:

https://github.com/Esri/angular-esri-map/blob/master/docs/app/examples/examples.html#L21

```html
<p>Demonstrates two-way binding of the center, and zoom properties.</p>
```

This is getting super complex.  I vote to mark this as 'wontfix'. Only joking.  Perhaps we shorten it down a bit more?
