### ISSUE TITLE
Update esriMap listeners for continuous map extent information?

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#74]
What if we were to add another (or replace) map event listener to **esriMap**, perhaps:
```javascript
map.on('pan,zoom-end', function(e){...});
```
Instead of waiting for a 1-time extent-change when the user is done panning or zooming, how about getting continuous feedback on the extent object?

My very brief trial of this still needs some massaging to get it right:
- it doesn't play nice with the `$scope.center` just yet, but seems fine when `extentChange` function binding is wired up
- any potential for performance issues sneaking in?
- if this is worth it, wanted to wait until any ongoing changes to **esriMap** get settled

![continuous-extent-change](https://cloud.githubusercontent.com/assets/4933392/9564549/3aae46ee-4e70-11e5-8042-5b2bfa016a55.gif)

Nothing pressing here, but a potential nice-to-have for the the _Map events_ and _No Basemap_ demos (and maybe the others, if bullet point 1 is addressed).  I'll be the 1st to admit that it's information overload for the user, but, you know, AngularJS folks like seeing things change and update :zap: fast. :smile:

**Comment by jwasil** [comment]
Just some additional notes for posterity's sake:

Something akin to this demo using JSAPI 4.x and dbind: https://ycabon.github.io/presentations/2015-uc-arcgis-js-api-road-ahead/demos/integration/dbind.html

I think the **esriMap**'s `$scope.inUpdateCycle` flag _might_ have something to do with the behavior mentioned in the 1st bullet point above.

**Comment by jwasil** [comment]
@tomwayson I don't think this is worth pursuing and supporting for v1.x.  I say let's close this since we know how to do it with JSAPI 4.x and it is documented in the property binding example and [test page](https://github.com/Esri/angular-esri-map/blob/master/test/property-binding.html).

**Comment by tomwayson** [comment]
agreed. thx.
