### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#78]
This will help w/ #18 as I think it will be used by [gh-release](https://www.npmjs.com/package/gh-release).

Get the history from the [releases](https://github.com/Esri/angular-esri-map/releases) and put into the format from either [esri-leaflet](https://github.com/Esri/esri-leaflet/blob/master/CHANGELOG.md) or [keep-a-changelog](https://github.com/olivierlacan/keep-a-changelog).

**Comment by jwasil** [comment]
For the initial commit, I've followed a hybrid approach between **keep-a-changelog** (used primary concepts like "Added", "Changed", "Fixed", etc.) and **esri-leaflet** (used "New Demos").  Both are great examples of starting points, thanks for pointing them out @tomwayson.

**Comment by jwasil** [comment]
Resolved via 05fc7414f0da05987a2ff12d5da81b6c28963d06
