### ISSUE TITLE
Run tests before proceeding w/ release script

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#84]
wire up `npm test` to `gulp test` and run that before releasing

**Comment by tomwayson** [comment]
may also want to: 
- have a test serve task that only serves test html files
- have current serve task watch test html files for changes and reload them?

**Comment by jwasil** [comment]
@tomwayson yes your above points are good ideas; the current serving that's going on in `gulp test` isn't very convenient when actually developing and working on tests

**Comment by jwasil** [comment]
:+1:
