### ISSUE TITLE
Write e2e spec for test/set-center-zoom.html

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#85]

**Comment by jwasil** [comment]
While working on this test, I suggest going ahead and upgrading the test page to Angular v1.4.4.  This test is still on v1.2.26 and doesn't work with the **esriMap** `$scope.$watchGroup`.

**Comment by jwasil** [comment]
Should also replace zoom `<select>` options built by an `ng-repeat` with `ng-options` to make sure the select element isn't empty when the scope is updated ([more info](https://code.angularjs.org/1.4.4/docs/api/ng/directive/ngOptions)).  This should be changed in both the example and test pages.

**Comment by jwasil** [comment]
resolved in c8659fce94a94c5361a4cb047410b7cf0c4c87e4

**Comment by tomwayson** [comment]
I pulled these down and ran them. Great work! 

I've been wanting to make that `ng-options` change for a long time, so I'm glad you added it.
