### ISSUE TITLE
Write e2e spec for test/feature-layers.html

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#87]
Only way I can think to do this is to interrogate the map's SVG for the existence of elements that represent the layers.

Probably want to add the "Show Trees" checkbox functiontionality from [the examples page](http://esri.github.io/angular-esri-map/#/examples/feature-layers).

**Comment by jwasil** [comment]
added "Show Trees" checkbox functionality as suggested above;

resolved in 30ac816a07ba765ffebe643228e46ec9ea69a8d0
