### ISSUE TITLE
Write e2e tests for legend directive

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#88]
Not sure if we want to do this on test/legend.html as the features services from the sample server in that page are pretty flaky. 

Could just add a test to the existing web map spec or add a legend to test/feature-layers.html and add a test to that spec when writing it.

**Comment by jwasil** [comment]
Note to assignee: feel free to work on this in the [additional-integration-tests branch](https://github.com/Esri/angular-esri-map/tree/additional-integration-tests).
