### ISSUE TITLE
Write e2e spec for other test pages

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#89]
These test pages are lower priority, but it would be great to have specs for them:
 - [x] test/additional-map-options.html
 - [x] test/deferred-map.html
 - [x] registry-pattern.html

**Comment by jwasil** [comment]
Note to assignee: feel free to work on this in the [additional-integration-tests branch](https://github.com/Esri/angular-esri-map/tree/additional-integration-tests).

**Comment by jwasil** [comment]
Also:
- [ ] test/add-remove-layers.html (see #96 for somewhat related work)
