### ISSUE TITLE
Update filenames and titles for consistency

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#91]
Should we change a few filenames among the example and test files for consistency?  I believe the items that do not match are limited to the following:

app/examples/ | test/ | proposed changes to app/examples/
------------ | ------------- | -------------
basemap.* | set-basemap.html | set-basemap.*
center-and-zoom.* | set-center-zoom.html  | set-center-zoom.*

Additionally, I'm curious about updating example and test page `<h*>` title text to be the same among related pages.  For example, consider:
- `<h2>Basemap Example</h2>` (app/examples/basemap.html), even though the link in the Examples TOC page is "Set Basemap".
- `<h2>Set Basemap</h2>` (test/set-basemap.html)

If we agree to making changes:
- [x] Update relevant route paths and properties in **appConfig.js**
- [x] Update title text in individual & related html files
- [x] Update links in Examples TOC page (?)

**Comment by tomwayson** [comment]
I agree with your proposed changes. I'd say go ahead and add these changes to #92.

**Comment by jwasil** [comment]
:+1: thanks for chiming in

**Comment by jwasil** [comment]
Done on PR #83
