### ISSUE TITLE
Normalize geographic center coordinates in esriMap module

### ISSUE THREAD

**Issue by jwasil** [Esri/angular-esri-map#93]
I propose that the **esriMap** module [`updateScopeFromMap` function](https://github.com/Esri/angular-esri-map/blob/master/src/directives/esriMap.js#L7) normalize the geographic center coordinates.  Consider the screenshot below, where the longitude is greater/smaller than +/-180 after panning west from the initial map extent over CA.

![image](https://cloud.githubusercontent.com/assets/4933392/9838040/9eeccf28-5a18-11e5-98ed-262a2703ccf9.png)

The change could be:
```javascript
...
if (geoCenter) {
    geoCenter = geoCenter.normalize();
    scope.center = {
    ...
```

Thoughts?

**Comment by tomwayson** [comment]
uh, yeah, that looks bad! I didn't even know `normalize()` was a thing. I'd say let's do it.

**Comment by jwasil** [comment]
Cool. I can verify that it's a quick fix for the sake of the geographic extent center values; no problem with normalizing a point.

On a related note--I just couldn't let it go (_typical_)--I looked at the [esriMap extent](https://github.com/Esri/angular-esri-map/blob/master/src/directives/esriMap.js#L186) values.  The `xmin` and `xmax` values also continue to increase or decrease in a similar manner.  Do we want to fuss over this?

Normalizing an extent will do the job, but if it crosses the dateline, we get 2 normalized extents.  Then again, since this only applies when an extent-change handler has been bound and we provide the entire event object, we could continue to leave the onus on the developer to deal with normalizing if they really wanted to...

**Comment by tomwayson** [comment]
Hm.. good question. For extent, I tend to think that the onus should be on the developer.

**Comment by jwasil** [comment]
Alright, agreed. Thanks for the feedback, I needed a sanity check on that one.
