### ISSUE TITLE
$scope.$watchGroup requires Angular 1.3+

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#95]
We need to either update the README, CHANGELOG, and release notes (of whichever release that landed in) w/ supported versions, or revert esriMap to use `$scope.$watch()` w/ a function.

**Comment by tomwayson** [comment]
Changes in 1.3:

https://keyholesoftware.com/2014/11/17/new-features-in-angularjs-1-3/
http://ng-learn.org/2014/06/Migration_Guide_from_1-2_to1-3/

Drops support for IE8.

Basically this comes down to what is the minimum version of Angular we will support at v1.0.0.

Not sure yet.

**Comment by tomwayson** [comment]
Also, once we decide on a minimum version of Angular to support, one idea would be for the test pages to use whatever is the *minimum* version of Angular (and possibly minimum version of the JSAPI too???) that we will support and the docs pages could use the *latest* versions of those libraries.

**Comment by tomwayson** [comment]
Looks like 1.3 was also the version in which these good things landed:
 - [bindToController](http://blog.thoughtram.io/angularjs/2015/01/02/exploring-angular-1.3-bindToController.html)
- [improved browserify suppor (1.3.14)t](http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support)

And supporting IE8 sucks, so I vote 1.3 (and *maybe* 1.3.14) as minimum supported version.

Anyone need Angular 1.2 and/or IE 8 support?

**Comment by tomwayson** [comment]
Decision min supported versions:

Angular v1.3.0 
ArcGIS API for JavaScript v3.11

 - [ ] update README accordingly
 - [ ] update all test pages to use those versions
 - [ ] find the release that required the update to v1.3 and make a note in the changelog/release notes

NOTE: docs site will continue to use latest versions of Angular and ArcGIS API for JavaScript.

**Comment by jwasil** [comment]
Note: For the _test/deferred-map.html_ page, I am taking advantage of the **esriLoader**'s optional url argument to specify JSAPI v3.11, since v3.14 is hard-coded [here](https://github.com/Esri/angular-esri-map/blob/master/src/services/esriLoader.js#L35).

**Comment by tomwayson** [comment]
For that test page, using the optional url arg is the way to go, but yes, this probably should eventuallly go into a config constant provider or something - let's review that while refactoring in Beta 6.
