### ISSUE TITLE
Replace feature layer definition expression w/ options

### ISSUE THREAD

**Issue by tomwayson** [Esri/angular-esri-map#97]
It would be best to be consistent w/ esriMap and get all options from a single attribute (`map-options`) that can be read from either an object scope property or an inline JSON string.

Should also update test spec to verify that the layer is initialized according to the options sent.

**Comment by jwasil** [comment]
Sounds good--I'm on it.

**Comment by jwasil** [comment]
The new `$scope.visible` is a good addition and I'm thinking to leave it alone as-is on the isolate scope.

I'm adding a new `$scope.layerOptions`, and it will use function binding just as in esriMap.  We'll allow the user to specify `layerOptions.visible`, but `$scope.visible` will still take precedence (again, similar to esriMap).  However, there are some renegade constructor options that can be included in the JSAPI constructor that I am trying to decide if we want to support:
- editSummaryCallback: `function`
- infoTemplate: `Esri InfoTemplate` -- could handle in a similar fashion as esriMap's `mapOptions.infoWindow`
- resourceInfo: `object`
- source: `Esri LayerSource`

Also:
- className: `string` -- cool thing is this works without a problem
- other options that take `arrays` also appear to be evaluated as proper arrays -- success!

Any thoughts before I disappear down a rabbit hole?

**Comment by jwasil** [comment]
^ More I think about it, I'll just see what is feasible when working with inline JSON string or object scope prop for these unique option types.  Shouldn't be that big of a deal to follow similar patterns established in esriMap.

**Comment by tomwayson** [comment]
Agreed on you approach w/ `$scope.visible`.

As far as all the non-scalar options:
 - I'm glad to hear (and not really surprised) that the arrays are working. I'd expect that `resourceInfo` should just work as well since it's an object, right? 
- Yes, handle `infoTemplate` the same way we handle it in the map directive. This should work even better than that b/c there's only one InfoTemplate class.
- `source` - I don't know how this is used, ignore for now unless there is an obvious use
- `editSummaryCallback` - Ultimately I'd say make this it's own function bound  parameter - just like the map's 'load' and `extent-change` attributes. however, since we don't currently provide any API for editing

**Comment by jwasil** [comment]
Thanks for your input.

- `source` is not very clear to me either ([LayerSource docs](https://developers.arcgis.com/javascript/jsapi/layersource-amd.html)); skipping for now to avoid requiring in another AMD module. Those who want it could follow the object scope property style and set it up themselves.
- `editSummaryCallback`: valid point regarding this repo not providing an API for editing; skipping for now.

**Comment by tomwayson** [comment]
BTW, ultumately I'd like to keep definition expression as a one way bound scope variable and watch it for changes and call setDefinitionExpression() in the layer, much like the visible attribute. Doesn't have to happen at this time.

**Comment by jwasil** [comment]
Nice, something along those lines was on my mind too, but less clearly articulated and lost in the haze of the enigmatic `LayerSource`.  How about we pull that out into another issue?  (#100)  Reached 100, achievement unlocked :trophy:.

**Comment by jwasil** [comment]
The recent commit message mentions that this has been resolved, but actually I will still be updating the e2e test spec in upcoming commits.
